### ISSUE TITLE
[FEATURE] Status view: Open file in different editor

### ISSUE THREAD

**Issue by franciscolourenco** [divmain/GitSavvy#1124]
I'm trying to use Sublime + GitSavvy as a git client, while using VSCode for editing (support is much better for certain languages). One of the few drawbacks I've found, is when opening files from the status view. I would like to open them in VSCode instead of Sublime.

Is is a possibility to make files open in a different editor, or simply make files open with the default file handler instead of opening them in a buffer?

Thanks!

**Comment by kaste** [comment]
Everything is possible but with limited resources this is sure pretty low-priority. High effort, low impact. One UX comes to mind how would you switch this behavior: now I work in Sublime, now I work with GitSavvy as a companion.  And don't "they" say: Ah, git integration is sooo good in code, and it's open source.

**Comment by franciscolourenco** [comment]
@kaste I would say this would be an opt-in setting. Is GitSavvy open to include this feature, given a PR?

**Comment by stoivo** [comment]
@franciscolourenco No. I dont want to polute GitSavvy with code like open on vs, open in x, open in y, etc. What I sugguest is that we build a small package which can do this. 
I use sublime most of the time. From time to time I need to open a file in VScode because it is better with typescript. Therefor I build https://github.com/stoivo/sublime-open-in-vscode a small plugin which open current file in VScode. When it gets more mature we will release it.  I would accept a PR the which whould expand the selection to the full path and open that file is VScode. Please open a PR there and we can contine the develpment there. 

I will close this issue and PR

**Comment by franciscolourenco** [comment]
It doesn't have to be specific to vscode. It could be to open file in the default application. 

Implementing it in stoivo/sublime-open-in-vscode would mean one couldn't use the `o` shortcut from GitSavvy right?

In any case I've implemented this in my fork, scratches my itch, even though opening and closing files is not nearly as quick. Still missing Sublime+GitSavvy for that reason.

Thanks for the reply.

**Comment by stoivo** [comment]
We could implement a command simial to git savvys GsStatusOpenFileCommand and overwrite the `o` key binding with 
```
    {
        "keys": ["o"],
        "command": "vs_open_from_gitsavvy_status",
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "git-savvy.status meta.git-savvy.status.section meta.git-savvy.status.file" }
        ]
    },
```

**Comment by kaste** [comment]
That's exactly what @franciscolourenco should have done. Not a fork but an add-on!

**Comment by kaste** [comment]
But *we* don't maintain it.

**Comment by franciscolourenco** [comment]
@kaste thank you, @stoivo was pretty clear, no need for a repeater.
