### ISSUE TITLE
GitSavvy future after Sublime 3.2

### ISSUE THREAD

**Issue by crisp2u** [divmain/GitSavvy#1127]
Hello,

I'm curious on how do you guys see the future of GitSavvy now that Sublime has started integrating Git in the last update ? More info about the new features can be found [here](https://www.sublimetext.com/docs/3/git_integration.html)

Thanks

**Comment by stoivo** [comment]
Sublime will most liky never add that many of the features GitSavvy has. 

As I see it, these are the new features Sublime Ships.
> Side Bar

We chould never to that since it's not a part of the API.

> Status Bar

It is not cofigurable, not that our is but it all abount you prefference.

>  Diff Markers

I know gitgutter did this but I know feel like I need it so ¯\_(ツ)_/¯  I might keep it enabled, or maybe disable it.

>  Sublime Merge Integration

It is like any other Git GUI tool, exect:  make but the same devs as Sublime Text, Perfect integration with Sublime Text. 
I don't think I would switch since I prefer to have the keybord as my input source. Maybe Sublime has some keybinding but not anything I know.

You have tools like Tower, GitKranken, Github dessktop which is other GUIs, https://www.sublimerge.com/sm3/ or https://packagecontrol.io/packages/Git which are alternative  Sublime Text plugins.

So nothing game changing.

What about you?
