### ISSUE TITLE
GitHub issues integration

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#14]
- [ ] list all issues for remote repository (special view)
- [ ] syntax highlighting
- [ ] open new issue (special view)
- [ ] close issue
- [ ] view details for issue, including comment history
- [ ] add comment
- [ ] view issue in browser

https://developer.github.com/v3/issues/

**Comment by yyyc514** [comment]
I've been looking at this a little.  You didn't have a mockup laying around, did you?

**Comment by yyyc514** [comment]
Since results are paged from the server we'd need to support paging somehow so that would have to fit in the UI.

**Comment by yyyc514** [comment]
I assume we'd allow paging by keystroke... thoughts?

**Comment by yyyc514** [comment]
I was imagining a detailed view and then less detailed view that you could toggle.  Idea for less detail:


```
GITHUB: divmain/GitSavvy

#139   Github Integration broken? [question]
#137   How to tell GitSavvy to forget git repository? [ux]
#136   TypeError: object of type 'NoneType' has no len() [bug] [investigate]
#135   Diff current file
#133   Inline diff adding multiple instances of the same row [bug]
#131   Easier to read branch summary on status view [ux]
#127   Support for non-UTF-8 [new feature]
#125   textwrap.dedent
#119   feature: allow using your own COMMIT_EDITMSG syntax
#117   fix: cursor should not jump when toggling remotes
```

**Comment by yyyc514** [comment]
![screen shot 2015-03-25 at 10 02 59 pm](https://cloud.githubusercontent.com/assets/6473/6839145/bcdb2062-d33a-11e4-8ee0-939d3cf54508.png)

Detail example.

**Comment by yyyc514** [comment]
Thoughts?

**Comment by yyyc514** [comment]
Idea for adding comment:

```
What makes you feel the Github integration is broken?  This was fixed in #139.

## also: [CLOSE ISSUE]

## Commenting on: #139 Github Integration broken? [question]
## To save your comment press SUPER-ENTER. To cancel just close the window. 

---------------------------------------
* yyyc514 commented 33 minutes ago:
 
  Thoughts?


---------------------------------------
* yyyc514 commented 2 hours ago:
  
I was imagining a detailed view and then less detailed view that you could toggle.  Idea for less detail:


``
GITHUB: divmain/GitSavvy

#139   Github Integration broken? [question]
#137   How to tell GitSavvy to forget git repository? [ux]
#136   TypeError: object of type 'NoneType' has no len() [bug] [investigate]
#135   Diff current file
#133   Inline diff adding multiple instances of the same row [bug]
#131   Easier to read branch summary on status view [ux]
#127   Support for non-UTF-8 [new feature]
#125   textwrap.dedent
#119   feature: allow using your own COMMIT_EDITMSG syntax
#117   fix: cursor should not jump when toggling remotes
``

```

**Comment by yyyc514** [comment]
Or did you imagine we might do the add comment view inline inside the listing of comments when viewing an issue?

**Comment by yyyc514** [comment]
Should each switched page result in a HTTP request to load the latest or if we've just visited all x pages should we serve them up cached and fast?  (i.e., should the interface cache the issue as they are paged, or pretty much run a HTTP request every single time)

**Comment by yyyc514** [comment]
```
GITHUB: divmain/GitSavvy

-------[ Page: 1 of 1 ]------------------------------------------------------------------------------------
#139   Github Integration broken? [question]
       opened by wldcordeiro
-----------------------------------------------------------------------------------------------------------
#137   How to tell GitSavvy to forget git repository? [ux]
       opened by freexo
-----------------------------------------------------------------------------------------------------------
```

Paging idea.

**Comment by yyyc514** [comment]
Well we wouldn't need it if it was 1 of 1, but you get the idea.

**Comment by divmain** [comment]
I hadn't planned on tackling this for awhile, so after reading your comments, I'm stopping now to consider what the goals should be here.  If in-Sublime functionality won't add anything (in UX or functionality) to existing workflows (open GitHub in a browser, switch between browser and Sublime), we should re-evaluate the scope of the feature.

So, in what way can we improve user workflows by utilizing Sublime extensibility?  If all the results will be paged and each "next-page" will require an HTTP request, our UX will almost certainly fall short of GitHub in the browser.  The only boon there is that we don't have to press `Super-Tab`.

A couple of  thoughts for what we could do, and how it would be an improvement on what we have now:

- Don't create a new interface; instead, just make it easy to get to an issue in the browser through a Sublime quick panel.  This gives us a more organic workflow, where we can look-up and reference issues (with fuzzy-string matching) without having to open the repo, click on issues, and search through the list for what we want.
- Create a new interface.  Additionally, automatically traverse and cache all pages of issues, and use this for an "offline" issues experience (when in an airplane, no wi-fi, etc).  Offline would have to be read-only, as otherwise we'd have complex syncing issues to tackle.

**Comment by yyyc514** [comment]
> Don't create a new interface; instead, just make it easy to get to an issue in the browser through a Sublime quick panel. 

This really doesn't work without some sort of caching (for larger issue lists)... as the only thing a single request can get you is a list of of top xx issues.  I'd assume that would be a problem with the existing tab complete issues we use on the commit page also.  Caching the list would be helpful for those other features that reference issues (like commits).

> . Additionally, automatically traverse and cache all pages of issues, and use this for an "offline" issues experience (when in an airplane, no wi-fi, etc).

Are you talking about caching the issue meta-data or caching the HTML pages themselves?

> Create a new interface. 

Paging in a view is actually pretty easy (if we decide on keystrokes and UX), but if we kept a cache we could avoid the paging entirely and just show the entire list of issues in either a view or a quick panel (which I haven't fallen in love with yet, but I need to use more - the fuzzy search is nice).

> cache

Any thoughts, preferences on this?  project_dir/.GitSavvy/cache/* ?  I'd also like to have a global settings file that we could store state in... so that some settings could be sticky between views.

**Comment by yyyc514** [comment]
> I hadn't planned on tackling this for awhile

Sorry to push it into the limelight - was looking for another (new) interface to work on to flesh out my interface ideas. :-)

**Comment by yyyc514** [comment]
If we scoped this to JUST a quick panel where would we show the syncing status of issues, when they were last refreshed, etc?  I feel like you'd need some sort of manual refresh (if not auto) - and some way to trigger/check that, no?

**Comment by divmain** [comment]
> Are you talking about caching the issue meta-data or caching the HTML pages themselves?

Issue JSON.  We shouldn't be touching HTML at all.

> Paging in a view is actually pretty easy

I'm not really talking about technical feasibility, I'm talking about the value proposition.  What I was getting at before is that, if the results are paged and each page event requires an HTTP request, the UX for this inside Sublime will be worse than UX in the browser.

If that's the case, we should reduce the scope of this feature, i.e. make it as easy as possible for the user to get where they want to go on `github.com` in relation to their current project.

Caching is problematic by nature.  If an issue has changed and the local metadata related to that issue is stale, the UX in Sublime will be worse than in the browser.  Manual refresh will take an extra step, which is a worse UX.

If, however, GitHub responds to API requests in a reasonable time-frame, and if we can collate the JSON "pages" into a single data-structure in a reasonable time-frame, we might be able to deliver a subset of what this ticket originally proposed.

Here are some examples of what that sort of integration might give the user that would be an improvement on existing workflows:

- present the user a quick panel, where they can do fuzzy-string matching for issue description
- open a new issue from sublime
    + issue subject and/or body could be pre-filled depending on editor context at initiation
- generate reports of issues opened/closed since date X

**Comment by yyyc514** [comment]
>  I'm talking about the value proposition. What I was getting at before is that, if the results are paged and each page event requires an HTTP request, the UX for this inside Sublime will be worse than UX in the browser.

Not necessary, but likely.  I get your point.

> Caching is problematic by nature. If an issue has changed and the local metadata related to that issue is stale, the UX in Sublime will be worse than in the browser

Disagree completely, at least for how I'm imagining the cache would be used.  If you're looking up issues (by title) to attach to issues or to launch a web browser the cache freshness starts to matter a lot less.   We know issue #'s can't change, and I'd wager titles don't change super often... therefore if you only cached title, issue #, URL, only 33% of your data even has the remote possibility of being out of date.  And if someone is searching by title what they really care about is the last title they were aware of making stale data perhaps even a blessing.

It also seems even for large projects (ala, Rails) that keeping the cache fresh would be easy.  The "recently changed" issues on Rails (closed + open) can be retrieved with 1 or 2 HTTP requests.  Perhaps several requests to prime the feature and then when the feature is engaged one quick request to get the latest changes because presenting the issue list.

Thoughts?

> If, however, GitHub responds to API requests in a reasonable time-frame, and if we can collate the JSON "pages" into a single data-structure in a reasonable time-frame, we might be able to deliver a subset of what this ticket originally proposed.

I can already feel the delay from a single request... I wouldn't want the app to freeze for more than 1 or 2 requests... which fits perfectly with my caching strategy mentioned above.  Although for tiny/smaller projects those 1-2 requests might potentially hold all the data, that is true.

**Comment by stoivo** [comment]
@yyyc514, I like you thinking!

**Comment by yyyc514** [comment]
Thanks.

**Comment by divmain** [comment]
Have decided this is out of scope for GitSavvy.  Could be implemented as a GitSavvy plugin.  In my case, I've discovered http://overv.io for issue management, and I doubt anything I put in GitSavvy (aside from the light integration that already exists) could provide a better issue management experience.
