### ISSUE TITLE
Add .sublimelinterrc file with recommended PEP8 settings to aid contributors

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#151]
Suggestions:
- longer line length
- possibly ignore some warnings and such that come up a lot that aren't a big deal? (no idea here, I just started using it)

**Comment by divmain** [comment]
I didn't know this existed :)

I agree, some of the PEP8 guidelines are too stringent.  I generally try to keep under 100 characters instead of 80.  Un-used imports also need to be explicitly allowed because of the `__init__.py` modules that are making submodules accessible.

**Comment by yyyc514** [comment]
> I didn't know this existed :)

You're welcome. :grin:

**Comment by p3lim** [comment]
You know, some of the settings like tabs vs spaces and vertical rulers could be customized on a per-project level.
Since you're most likely (and all the contributors the same) are developing this in Sublime Text, adding a `.sublime-project` file could aid those who don't want to use linting plugins.

**Comment by yyyc514** [comment]
Couldn't hurt but I don't know why someone would refuse to use listing when it's so nice in Sublime.
