### ISSUE TITLE
Git blame line walker

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#152]
Feel free to rename.  References #102.

When viewing a file in git blame I'd like to hover over a group of lines and then go back in time to each prior version of the file and do a git blame there while preserving my cursor position.  So if the git blame said the prior commit was 'abc' then I hit say '<' (back) and then I'm looking at the blame from abc^ (the parent commit of ABC)... so I can find out who is truly responsible for a change even if there is a lot of churn in a single file.

This would of course also survive renames, etc... since that information is included in git blame.

**Comment by yyyc514** [comment]
A very rough first pass: 
https://github.com/yyyc514/GitSavvy/tree/feature/blame_walker

Features:

- "<" steps back to find the previous change to a given line
- refocuses the view on the old version of the line
- stepping back works even across file renames
- yells at you when you can't go back any further
- yells at you if you haven't picked an exact line

Questions:

- What keystroke should we use here?
- Should there be help to explain keystrokes to people or should they need to read the docs?
- What about stepping forward?

Since blame is a historical view there really isn't any real concept for stepping forward (from a given actual `blame` with no prior context), but we could keep track of your trail as you step back in time and then have another key to step forward.  The you could hit <> to flip between two revisions of the file... the  newer and older.

Thoughts?

**Comment by divmain** [comment]
For early feedback, either is fine since I can just hit "Compare" on the feature branch.  Keeping track of the trail sounds good - that info should be stored in the view settings to persist Sublime restarts.

For views like this, the UX to present contextual help can be complicated.  So I've preferred to take the user to relevant documentation when they do `GitSavvy: help`.  I'm open to other ideas, but user docs are probably the place to start.

`<` and `>` are fine for walking back and forth.

**Comment by benmosher** [comment]
:+1:

**Comment by stevage** [comment]
This sounds awesome - how can I try it?

**Comment by stoivo** [comment]
maybe we can use some of this https://github.com/georgebrock/git-browse

**Comment by rchl** [comment]
Long time without progress. It would be really nice to have this feature. Do you need some help with implementing it?

**Comment by stoivo** [comment]
If you have the time to look at this we would be very thankful.

**Comment by rchl** [comment]
I wonder what original patch author is up to though. Wouldn't want to reinvent the wheel.

**Comment by divmain** [comment]
@rchl, the codebase has changed significantly since this was last explored, so anything is going to be a reinvention.  This will most likely involve a significant refactor of the blame blame view.  If you'd like to take a look, I'd be happy to answer any questions as you go along.  I'm often online in the Gitter channel, so you can find me there.

**Comment by randy3k** [comment]
close by #661
