### ISSUE TITLE
Quick stage and commit should work from viewing a diff

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#160]
- quick stage current file and commit works from a diff of a single file (triggered via diff single file)
- quick stage current file and commit does not work from a diff of a single file (triggered via "diff")

I think (in this view only, perhaps) we should have a "git: quick stage all and commit" that does that.  This inconsistency seems very strange.  I was hung up on it for a few minutes before I realized the subtle difference that it was a FULL diff that happened to be a single file vs a single file diff.

**Comment by divmain** [comment]
Want to clarify, make sure I'm understanding.  You expected to be able to run `git: quick stage current file and commit` from within the full unstaged DIFF view, correct?  I suppose I can see how it might be disorienting if you've only changed a single file - the contents would look basically identical.

I'm not sure how I feel about a contextual palette command that is only available in this specific context.  We're not doing that anywhere else, although I'm open to the idea if there are enough solid use cases.  But since it'd be the only one, discoverability would probably be next to nil.  I'm wondering if there'd be a natural key-binding that could be used for this, although that suffers the same problem.

Last thought for now - the solution could really be to have an always-available `git: stage all and commit` palette command.  I wouldn't use it myself, but the name makes it obvious what it does, and they could always bail out from the commit window.
