### ISSUE TITLE
Why plugin use git from /usr/bin/git

### ISSUE THREAD

**Issue by max-mykhailenko** [divmain/GitSavvy#163]
```
> which git
/usr/local/bin/git

> where git
/usr/local/bin/git
/usr/bin/git

> git --version
git version 2.3.4

> /usr/local/bin/git --version
git version 2.3.4

> /usr/bin/git --version
git version 1.9.5 (Apple Git-50.3)
```

Where I can configure it?

**Comment by divmain** [comment]
I'm surprised this hasn't come up before!  I did make this configurable, but forgot to add the documentation.  I've done that now.  If you're on master (not installed through the package manager), see [here](https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L9-L12).  If you have GitSavvy installed via the package manager, the setting is `gitPath` instead of `git_path`, which was a typo.  I may push out this change in a small update, if you want to wait.

**Comment by max-mykhailenko** [comment]
Config 
```
{
  "git_path" : "usr/local/bin/git",
  "gitPath" : "usr/local/bin/git",
  "show_panel_for" : ["pull", "push"]
}
```

result when push
```
> /usr/bin/git push
```

**Comment by divmain** [comment]
Did you restart Sublime?  GitSavvy will cache the path so it doesn't have to look it up for each command.  [Relevant code](https://github.com/divmain/GitSavvy/blob/3400c41494f7e0e17b983b098fdb972dd07e13bd/core/git_command.py#L139-L139).

**Comment by max-mykhailenko** [comment]
Today all works fine, thanks @divmain.
