### ISSUE TITLE
Attempting to discard staged file should not display destructive action prompt

### ISSUE THREAD

**Issue by dflock** [divmain/GitSavvy#165]
Trying to discard changes to a staged file doesn't work. If you try it - and you have GitSavvy set to prompt for destructive changes, it'll prompt you. If you say yes, the prompt goes away but nothing happens - the changes aren't discarded. If you don't have it setup to prompt, nothing happens at all.

You have to unstage the change first, then discard.

It would be nice if GitSavvy silently unstaged the file for you, then did the discard.

**Comment by divmain** [comment]
This was an deliberate choice, except for that part about the destructive action prompt of course ¯\_(ツ)_/¯).  This is mostly because I rarely find myself wanting to discard a file I've already staged.  It seemed more likely that hitting discard on a staged file would be a mistake, versus it actually being intentional.

If nothing else, the prompt should be fixed.  Is this something that you run into often?  My patterns may not be in the majority here, so I'm open to discussing.

**Comment by dflock** [comment]
No, not something I do often, so I'd be OK with just fixing the prompt, I guess.

**Comment by divmain** [comment]
Alright, it will no longer display the destructive-changes warning for staged files, and will also show more specific messages when you're discarding untracked vs unstaged files.
