### ISSUE TITLE
Exclude whitepsaces from diff

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#173]
It might be a nice addition to be able, if needed, to exclude whitespaces from diffs. Sometimes you are modifying someone elses' code and they don't follow the same standard and reviewing changes is a bit of pain if it has tons of unnecessary whitespaces changes (I have my editor to trim trailing whitespaces).

**Comment by divmain** [comment]
One possible issue: for those that use the diff view for staging hunks, whitespace-only hunks would no longer be visible.  @hanoii do you envision this as a global setting or a separate command.  I lean towards the former.

**Comment by hanoii** [comment]
Ideally I think what might make it great is a hotkey toggle, say 'w', so you type w and you toggle between showing/hiding whitespaces hunks right in the diff view. It that's not easy/too much work, I think a separate command is better. Maybe you can have a global setting that can enable the command so it won't bother those that never use this.

In my normal workflow, I only use "git diff -w", which is what I am aiming for, very seldomly, but when I do it, it's because it's almost mandatory to properly review a patch, so having a global setting would be very impractical.

**Comment by divmain** [comment]
A toggle is a good idea.  And staging-functionality could be pretty simply disabled when whitespace is not shown.

**Comment by hanoii** [comment]
Why would you disable the staging-functionality? I might still be interested in stage/discard those hunks that are shown when you hide whitespaces.

**Comment by divmain** [comment]
Take the following example:
```
$ git diff
diff --git a/things.stuff b/things.stuff
index 131164f..fcb775b 100644
--- a/things.stuff
+++ b/things.stuff
@@ -1,6 +1,7 @@
 test
 file
-test
+  test
+additional line
 file
 Python 2.
 Python 2.7

$ git diff -w
diff --git a/things.stuff b/things.stuff
index 131164f..fcb775b 100644
--- a/things.stuff
+++ b/things.stuff
@@ -1,6 +1,7 @@
 test
 file
   test
+additional line
 file
 Python 2.
 Python 2.7
```

GitSavvy uses the output of the `git diff` command both for display and for taking action when the user attempts to stage/unstage.  If using `-w`, the applied diff will actually be wrong and you'll get a partial stage.  That's if it even works at all - since the surrounding context is incorrect, Git would likely refuse to apply the patch.

**Comment by hanoii** [comment]
I wouldn't mind the partial stage, I have created a lot of patches with git diff -w and they always applied cleanly. I wonder if your example would actually fail at all, even if it does, it's a very remote possibility that I'd leave it for the user to resolve it. I would still appreciate the ability to stage/unstage hunks even in -w.

**Comment by divmain** [comment]
A partial stage would make for bad UX, as it would break expectations for many users.  I'll experiment with this a bit and let you know.  It may be we can make this configurable.

**Comment by asfaltboy** [comment]
Just wanted to add that this issue is critical to me; this is because a whitespace diff for one "big file" (~1k rows) with inconsistent whitespace (e.g checkout out from a bad/windows commit) is very very slow. While running `git diff` is actually very quick. A simple setting to turn off whitespace diff globally would rescue me - can I submit a pull request?

**Comment by stoivo** [comment]
I am working on this
