### ISSUE TITLE
Problem with reload modules

### ISSUE THREAD

**Issue by stoivo** [divmain/GitSavvy#174]
Hi
I looked at the plugin and would like to work a bit on it. I have a problem. When I run 
GsReloadModulesDebug

My other pluggins and  Git, stop working 
https://gist.github.com/stoivo/dd533477ab97e07ba782
This is the log from console. I think it is something with sublime.sublime_api.plugin_host_ready()

I am using a MAC 10.10.3 and sublime 3 Build 3083

**Comment by divmain** [comment]
Hi @stoivo.

`GitSavvy: reload modules (debug)` was meant as a short-cut for my own development, but it definitely isn't a requirement.  You can always close Sublime and re-open to load changes made to GitSavvy or any other plugin - this is what I did for some time.  Unfortunately, calling `plugin_host_ready` is necessary due to how GitSavvy is structured as a plugin.  I originally skipped that part, but the plugin would fail to reload all submodules correctly.

As far as I know `plugin_host_ready` is undocumented and unsupported, and there doesn't appear to be another option provided by the Sublime API.  If you're aware of another option, however, I'd be very interested in hearing about it.  And if there's another change that might help your particular use case, please feel free to re-open the issue!
