### ISSUE TITLE
Add option to globally disable "Git binary cannot be found" message

### ISSUE THREAD

**Issue by hzpc-joostk** [divmain/GitSavvy#194]
There is a problem when Git is not installed. I sync Sublime's User packages using Dropbox with my home computer. So today Sublime at home installed GitSavvy (GS) as it was not installed, yet. But Git is not installed (I was not planning to at home). It seems that GS is quite allergic to this situation. Because every change in view, menu or whatever triggers GS which will view the following critical message window:

![Critical: Sublime Text - Your Git binary cannot be found](https://cloud.githubusercontent.com/assets/10130907/8025940/987b3d90-0d66-11e5-8f9a-e134cc90403c.PNG)

This is **quite** annoying. :-) Maybe, as an improvement, GS could display this once per session instead of once per trigger. For now, the best would be installing Git on my PC.

**Comment by max-mykhailenko** [comment]
If you don't have git why you need synced sublime? Also you can add GS to ignored packages in sublime preference or in project preference (this I don't remember exactly) at home

**Comment by hzpc-joostk** [comment]
Max, I am using some other packages. I use sublime at home mostly for other stuff than programming, or just for (re)viewing source code to learn. Good idea about the Sublime preferences, I'll give "%appdata%\Sublime Text 3\Packages\Preferences.sublime-settings" a try instead of the one in subfolder ".\User". 

Maybe the message could be updated:
[git_command.py:146](https://github.com/divmain/GitSavvy/blob/4957ad71739b9352d084bb7f292df00ae1b91f7c/core/git_command.py#L146)
```python
msg = ("Your Git binary cannot be found.  If it is installed, add it "
       "to your PATH environment variable, or add a `git_path` setting "
       "in the `User/GitSavvy.sublime-settings` file. Or add GitSavvy "
       "to the `ignored_packages` setting.")
```

It seems that `sublime.error_message` only displays a critical window. Maybe a global `git_path_warned` boolean could be used to prevent displaying the screen over and over again:
[git_command.py:145](https://github.com/divmain/GitSavvy/blob/4957ad71739b9352d084bb7f292df00ae1b91f7c/core/git_command.py#L145)
```python
global git_path_warned
if not git_path and not git_path_warned:
    git_path_warned = True
```

**Comment by divmain** [comment]
Unfortunately, I don't think there's a great solution to this.  Adding an entry to the base `Preferences.sublime-settings` seems to be the best option for your specific case...

In my mind, this is a very small edge case.  Generally, if a user wanted GitSavvy installed but didn't want to use it or to install `git`, they would turn to `Package Control: Disable Package`.  Of course, in your case, that doesn't help - because it modifies ignored packages in your sync'd User directory.

This seems to be a pitfall not of GitSavvy but of the syncing solution.  Just to be clear, I'm definitely not trying to be pedantic or unhelpful here at all.  It is just an issue that is difficult for GitSavvy to solve itself.  I'm not comfortable with the suggested messaging behavior-change, due to the following scenario:

> A new GitSavvy user (and possibly new programmer) is attempting to setup their dev environment.  They initially see the message, and they attempt to set their `git_path` setting.  It works!

> But then they do some more tweaking, and now GitSavvy cannot find the `git` binary.

As things are now, they'd see the message again, and fix the problem.  If the behavior were changed, GitSavvy would fail silently and they'd be left confused and possibly give up.

One alternative would be to add a new GitSavvy option that allows the user to explicitly silence all "failed to find `git`" messages.  In your case, you'd just have to be careful on your dev machine not to move `git` or incorrectly change your `git_path` setting.  I'll leave this ticket open for a few days to consider if I'd like to go forward with this - I'm not sure it is a considerable-enough edge case to warrant its own configuration option.

**Comment by hzpc-joostk** [comment]
Hi @divmain, thanks for sharing your thoughts. I have found myself in confusion with something related in a different program. So implicitly silencing the warning was probably a bad suggestion. 

If I found myself in your position I would not put to much work on this issue/feature request as it is quite a specific situation which may affect other users. Perhaps I should just install Git on my home computer anyway. If only for hobby projects. :+1:

**Comment by divmain** [comment]
Hmm, thanks for letting me know you've seen something similar with a different plugin.  It's kind of a tricky thing, and makes me want to come up with a better syncing mechanism :).  I still think the setting may be valuable - let me know if you have additional thoughts, especially if you can think of other use-cases for silencing the message.  There may very well be situations I'm not considering!

**Comment by divmain** [comment]
After thinking about this a bit, I haven't found a way to make this intuitive.  Sublime should probably provide a mechanism to disable plugins even with settings synced across machines.  So going to go ahead and close this as out-of-scope.

**Comment by hzpc-joostk** [comment]
Sure, no problem! Cheers
