### ISSUE TITLE
Problem with --porcelain 

### ISSUE THREAD

**Issue by dlnsk** [divmain/GitSavvy#211]
git version 1.7.9.5
STATUS panel don't show current branch correctly.
I was research git output and noticed that `git status --porcelain -b` don't output branch name even with -b option.
So I recomend use `-s` instead `--porcelain`
https://github.com/divmain/GitSavvy/blob/master/core/git_mixins/active_branch.py#L31

**Comment by divmain** [comment]
@dlnsk git v1.7.9.5 should have same support for both `--porcelain` and `-b` flags.  `-s` flag is not guaranteed to be stable across git releases, which is why we use `--porcelain` where it is available.  Can you attach a screen shot with the specific problem, as well as any documentation you came across while digging into this?

**Comment by dlnsk** [comment]
@divmain yes I know that --porcelain generate stable output but screenshot will say more:
![git_1795](https://cloud.githubusercontent.com/assets/332778/8891050/8ea79fe8-3331-11e5-94b1-c0dfe437def2.png)

**Comment by divmain** [comment]
Huh, that's very strange.  I may have to do some testing to see where and when this behavior occurs.

**Comment by divmain** [comment]
Sorry for the delay, just circling back on this.  I've been looking at the [docs for your version of Git](https://git-scm.com/docs/git-status/1.7.9.5).  It does note that the status short-format will include a branch name if `-b` is included.  It goes on to note the differences between short-format and porcelain mode, and does not include a disclaimer about no branch info when using `-b`.

As it turns out, this was a bug in Git.  It was fixed in [1.7.10.3](https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.10.3.txt#L31-L33).  So my action item on this will be to add documentation that Git v1.7.10.3 is the lower supported version of Git.

**Comment by stoivo** [comment]
:+1:
