### ISSUE TITLE
Git merge UI quirk

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#241]
1. Select `git merge` from Shift-Cmd-P menu (what is that called...), using keyboard.
2. ...nothing happens...
3. Press any key.
4. Now a menu of branches to merge from pops up.

In step 1, if you use the mouse to click "git: merge", the menu comes up straight away.

Could be some interaction with other plugins - I have a few.

**Comment by divmain** [comment]
Huh.  Yeah, definitely cannot reproduce this (tested Mac, Windows, Ubuntu).  I feel like it has come up before, quite a long time ago.  Would recommend disabling other plugins, and turn them on one by one until the unexpected behavior returns.

**Comment by divmain** [comment]
Feel free to re-open if you determine this is caused by GitSavvy somehow.

**Comment by stevage** [comment]
Yeah, will do. Wish Sublime had more sophisticated plugin management -
disabling plugins one by one doesn't really work (and is very inefficient)
when it treats every syntax highlighting module as a plugin etc.

**Comment by ddevlin** [comment]
@stevage, there's probably no need to disable core packages like syntax files, if there was an issue there everybody would be experiencing it. The issue is much more likely to be with a third party package. 

You can disable Sublime Package Control managed third party packages in bulk like this:
- Opening the Package Control user settings file: `Super + Shift + P` > `Preferences: Package Control Settings - User`
- Copy the items from the list `installed_packages`.
- Open User Settings: `Super + ,`
- Paste the packages you want to disable into `"ignored_packages"`, e.g.:
```javascript
"ignored_packages": [
	// <PASTE NEW ITEMS HERE>,
	"Vintage"
],
```
- You can toggle packages on and off in bulk by commenting out lines in ignored packages and saving the file.
- You'll probably want to restart between package changes.

**Comment by stevage** [comment]
Ah, thanks. Well, interestingly I did briefly get to a situation where this minor issue went away. I slightly misapplied the instructions and removed everything from `installed_packages` except GitSavvy. When I added everything back, and also added all the packages to `ignored_packages`, the problem recurred.

Anyway, that's probably enough time chasing a pretty superficial maybe-bug. Thanks again for the Sublime support! :)
