### ISSUE TITLE
Allow 'c' for commit from inline diff page

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#255]
I frequently make a series of commits by staging different bits from the same file. Currently that workflow looks like:

1. `git status`
2. Select file, press `l`
3. Find a couple of bits to stage with `h`
4. Tab back to the status page
5. Press `c`, enter a commit message
6. Tab back to the diff page.
7. Resume from step 3.

How about removing steps 4 and 6? :) (I note in passing that a certain other git plugin for Sublime behaves this way...)

**Comment by sentience** [comment]
@divmain may disagree, but I don’t like the idea of adding key bindings (especially single character keys) for views that have nothing to do with what’s displayed by that view.

GitSavvy’s Commit and Quick Commit commands are already accessible everywhere via the Command Palette; have you considered adding a user key binding to invoke one of these?

**Comment by sentience** [comment]
Here’s how GitSavvy’s **Default.sublime-keymap** file creates key bindings that are only active within Inline Diff views:

```json
    {
        "keys": ["h"],
        "command": "gs_inline_diff_stage_or_reset_hunk",
        "context": [
            { "key": "setting.git_savvy.inline_diff_view", "operator": "equal", "operand": true }
        ]
    },
```

You can use the same approach to add your own mapping for `"c"`.

**Comment by stevage** [comment]
Mmm, fair enough. "that have nothing to do with what’s displayed by that view" is going a bit far though - commit is closely related by workflow to the inline diff page.

How do you get into GitSavvy's **Default.sublime-keymap** file?

**Comment by sentience** [comment]
@stevage If you want to add your own key mapping, then in Sublime go to **Preferences > Key Bindings – User**. This will open your personal key bindings file for you to edit. Initially it will just contain an empty array:

```json
[
]
```

You can add a new key binding for the GitSavvy Commit command:

```json
[
    {
        "keys": ["c"],
        "command": "gs_commit",
        "context": [
            { "key": "setting.git_savvy.inline_diff_view", "operator": "equal", "operand": true }
        ]
    }
]
```

That should do it!

To answer your question directly, I had a look at GitSavvy’s **Default.sublime-keymap** by browsing the source code for GitSavvy here on GitHub. You don’t want to edit that file directly, though, because it will be replaced every time GitSavvy is updated (not to mention the fact that it’s buried in the package’s ZIP file, so editing it in place is pretty difficult anyway).

**Comment by stoivo** [comment]
This may become a very common question, so maybe we should add some docs somewhere so new users can add it if they want to.

**Comment by divmain** [comment]
Added a new ticket for documenting custom GitSavvy key-bindings.  Closing this out.  Thanks for lending a hand, @sentience!
