### ISSUE TITLE
Not clear if console message is fresh when doing `git push`

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#256]
1. `git push`
2. Console pops open with message like "`/usr/bin/git push` failed with following output:...hint: 'git pull ...') before pushing again...."
3. `git pull`
4. Console remains open with the same message - nothing is appended.
5. `git push`
6. Console is still open with the same message. Did the push fail again? Is this an out of date message?

Suggestions:

1. Detect this particular case and close the console on pull
2. Write output on pull, if the console is open
3. Close the console before pushing, so at least you'd see it pop open again.

**Comment by stoivo** [comment]
What would you prefer? 

I think the first option is the best since if you want output from push and pull. We have a setting called: 

Add entries to this array (e.g. "pull" or "push") if you'd like the
output of these Git commands to always be shown in a panel.
```json
{
    "show_panel_for": [],
    "show_panel_for": ["pull","push"]
}
```

**Comment by stevage** [comment]
Yeah, I guess that's the best. I guess I intuitively expected that it would behave like this:

1. `git push` fails
2. Panel opens
3. Any other Git command that doesn't fail
4. Panel closes

The options aren't mutually exclusive though. It would kind of make sense to close the panel on successful operations, but also to always write output to the panel (regardless if it's open). Finally, some UI hint about fresh output would help - like a quick fade-in or glow-out for any new output.

(Yeah, I know I'm just dreaming up a lot of work for everyone, feel free to tell me go away. :))

**Comment by stoivo** [comment]
Currently we wipe the view and insert the new output to the same view. I think most of the users does not care about the output. But I prefer to see what I pull, which files. What other action would you like to see the output from?
fetch? merge?

**Comment by stevage** [comment]
That's a hard question. Definitely merge. Not fetch. Ideally, you'd get some sort of quick glimpse of output after every command (maybe fading away), and the output would stay open if it failed.

**Comment by divmain** [comment]
This is a bit more complex than it might appear, because for a given interaction with the UI, there are often several invocations of `git`.  The status bar at the bottom is updated with latest repo status, or if you're in a dashboard any number of commands will run to generate the text that you see.  So it can't be as simple as closing a panel if a Git command succeeds - usually this would mean that the panel would almost immediately close and you'd never see the failure.

The fade-in/glow animations won't be possible due to constraints of Sublime itself.

The one possibility is to generate a lot for every git command and append that to the panel, only displaying the panel on error or if a user requests it.  However, there'd be a lot of noise in that panel (due to the same reasons above) OR we'd have to add some sort of filter so that only the output of certain commands was piped to the filter.

Two less-complicated options to solve the original problem:
1) show a time/date tag whenever the panel shows with an error
2) the user makes sure to close the panel before trying again (this is what I do in my work-flow, and I don't think about it anymore)

One thing that may be helpful too, is the status bar.  In the case of pull, for example, it'll first say `Starting pull...`.  If the pull succeeds, you'll see `Pull complete.` as soon as that happens.  If it fails, you'll see the pop-up.

Thoughts?  I'm less inclined to add too much complexity here, but I agree the interaction is not as clear as it could be.

**Comment by stoivo** [comment]
Yes.

It will not add too much complexity here if we only do it for certain commands  like `pull`, `push`, `merge`, `fetch`? etc, And if one of these operation is done successfully close the panel or open the success panel if  `show_panel_for`: option is active

I think this can be implemented quite nicely without adding complexity

**Comment by stevage** [comment]
Thanks very much for the analysis etc. 

1. Adding a time/date helps a bit, but only after the user is aware that they are confused. That is, it helps resolve confusion, but it doesn't prevent it.
2. How about always closing the panel *before* any action? Then you'd have combinations like:
- push fail (opens panel) 
- pull (closes panel, then reopens if you have that option set); 
- push
-- succeeds (panel is either still closed, or closes again)
-- or fails (panel opens, or briefly closes, then opens again)

That seems simple, consistent, and intuitive?
