### ISSUE TITLE
"You are about to discard one or more files" - doesn't show file names

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#258]
When discarding a file, GitSavvy helpfully shows this message:

>You are about to discard one or more files.  This is a destructive action.  
>Would you like to proceed?  
>(you can disable this prompt in GitSavvy.sublime-settings)

It doesn't show the actual file names. Confirmations of destruction are better with as much context as possible...

(Side note: when I first starting using GitSavvy, I saw this a lot, as "d" seemed the intuitive key to press to view a diff. I'm very glad it's there.)

**Comment by stoivo** [comment]
I will change the note. 

And if you want to you can remap key is you would like to? I can make an example if would like

**Comment by divmain** [comment]
Hmm, changing this will require changing how the notification works, though I'm not necessarily opposed to that change.  @stevage, what would your ideal user experience look like here?  Here are my thoughts, though:

- we wouldn't want to just unilaterally list all files because
  + it adds a lot of noise to the message
  + there could be dozens or hundreds of files being discarded (for example, in the middle of a merge)
- we could cap it to four or five filenames, but this could lead people to assume that there aren't other files being discarded (even if we explicitly say so).  
- te could indicate the number of files being discarded, but this seems like a very minor improvement.
- to do that, we'd need to add some templating to the warnings, which will mean increased complexity.

@stoivo, I don't think he needs to remap the keys - he was just saying that this warning was useful when he first started with GitSavvy, since the mapped keys were not what he expected.

**Comment by stevage** [comment]
Few files:

>You are about to discard these 3 files:
>
>  README.md
>  index.js
>  src/lib/server.js
>
>This is a destructive action. Would you like to proceed?

Many files:

>You are about to discard 30 files:
>
>  README.md
>  index.js
>  src/lib/server.js
>  src/lib/another.js
>  ...and 26 others.
>
>This is a destructive action. Would you like to proceed?

(And yeah, I don't need to remap keys - my brain is trained now :))

**Comment by stoivo** [comment]
@stevage Good you leaned GitSavvy key-strokes. I just want you to know that it is not really hard to  remap any of the key-strokes.

Also I think it is a good thing to show the name of the filer you are about to discard. Most of the times I am discarding, it is only one file. Sometime I press cancel to check that I am not discarding wrong  file.

By what I have seen it looks like this is complicated to make.

**Comment by alextegelid** [comment]
> isn't it always just one file being deleted?
> - @stevage

I used GitSavvy for quite some time before I noticed it was possible to use multiple cursors when selecting files in the status view. Try it out 👌🏼

**Comment by divmain** [comment]
@stevage, I've decided not to move forward with this feature request.  After looking into it, contextual prompt templating looks to be a rather complex feature to implement.

I agree that the UX would be better with more context.  However, the user can cancel, look at their status dashboard (or elsewhere), and initiate action again if they so desire.  The gains here don't seem worth the increased complexity.  Sorry to disappoint!

**Comment by stevage** [comment]
Not a problem! Had no idea it would be complex when I suggested it.

**Comment by divmain** [comment]
Yeah, I wasn't sure at first either.  If the feature was simple to add, it'd be a no-brainer.
