### ISSUE TITLE
Suggestion: better controls when resolving conflicts

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#265]
Many a time when rebasing a branch, conflicts may arise (granted, it usually occurs with a stale branch).

Currently, when a conflict occurs, the rebase dashboard (which is the view the user is currently at) and other dashboards/commands become disabled until conflict is resolved. To resolve the conflict, usually the user will now navigate to status dashboard (or go full command line) and run his mergetool.

I suggest there should be some better integration with the rebase dashboard (perhaps adding shortcut to the mergetool command here, while disabling others) or with the status dashboard (alerting that git is currently in rebase mode); and adding commands to continue or abort the rebase.

Coincidently, a "merge mode conflict" will also benifit from a similar flow (a notification and commands to abort and continue).

**Comment by sentience** [comment]
I believe this is already the case. When the Rebase dashboard encounters a conflict during a Rebase, it displays check marks for all of the commits that have been replayed successfully, and then displays a X against the commit that could not be replayed due to the conflict. Under the commit description, there is displayed a list of the files in which conflicts occurred:
 
![rebase__conflict_shown](https://cloud.githubusercontent.com/assets/89772/10599924/5395467a-7752-11e5-9125-d419cb235b48.png)

You can then position your cursor on the conflicted file name, and hit M to launch an external merge tool, or hit one of the other displayed shortcuts to deal with the conflict:

![rebase__conflict_shortcuts](https://cloud.githubusercontent.com/assets/89772/10599940/82ed21ae-7752-11e5-9e2d-3917e2863d61.png)

Commands to continue or abort the rebase are also available:

![rebase__rebase_shortcuts](https://cloud.githubusercontent.com/assets/89772/10599951/ab80f99c-7752-11e5-9ecc-bb88c2a7b180.png)

**Comment by asfaltboy** [comment]
Oh wow, I missed this, must have been added in one of the latest version :+1:  !

**Comment by divmain** [comment]
I think it was part of the original rebase dashboard.  But it is easy to miss, if you don't notice the keybindings menu changing :)

**Comment by asfaltboy** [comment]
@divmain I just noticed that conflicts which arise from merging do not have the same options in neither status nor rebase dashboards; however, `git merge` *does* allow for [`--abort`](https://git-scm.com/docs/git-merge).

Perhaps that should be a feature? Specifically, we would have to add the following:

    A - abort
    y - use version from your commit
    b - use version from merge source commit

**Comment by divmain** [comment]
Yes, this surprised me the other day.  I never did add the functionality to the status dashboard.  Added issue #269.
