### ISSUE TITLE
Bizarre `status` display after move + recreate of a file

### ISSUE THREAD

**Issue by benmosher** [divmain/GitSavvy#273]
Note the weird `Client/webpack.config.js` in the STAGED section:
![screen shot 2015-10-23 at 3 51 33 pm](https://cloud.githubusercontent.com/assets/3709196/10703440/314579ac-799e-11e5-991e-4ed510ffbd75.png)

Seems that pesky `->` is showing up, because I renamed my existing `webpack.config.js` to `webpack.base.config.js` and then created and staged a "replacement" `webpack.config.js`.

**Comment by divmain** [comment]
Hm, could you give me a bit more context for this?  Maybe output of normal `git status` on the command line, and explain a little more what you mean by "move + recreate".

**Comment by benmosher** [comment]
Here's the vanilla `git status`:
![screen shot 2015-10-23 at 4 31 39 pm](https://cloud.githubusercontent.com/assets/3709196/10704257/92c3fe9c-79a3-11e5-9515-8588d144503a.png)

Transcript of my actions is analogous to

* Move the file: `mv webpack.config.js webpack.base.config.js`
* Recreate a new file at the same location: `echo "module.exports = require('./webpack.base.config') > webpack.config.js`
* Stage both: `git add webpack.*config.js`

Git (impressively) correctly identifies the rename and shows the "new" `webpack.config.js` even though the file "exists" in the previous commit.

**Comment by divmain** [comment]
Yeah, I think the only way Git will detect something as renamed is if a file at the old path does not exist (and the diff is sufficiently small).  Otherwise, it treats the renamed file as new, and gives you a big ugly diff for the "new" file at the old path.

I don't think there's any way around this.  Going to close out this ticket.  If I'm missing something here, please do re-open.
