### ISSUE TITLE
git push doesn't ask for ssl key passphrase

### ISSUE THREAD

**Issue by atk** [divmain/GitSavvy#285]
I have a repository at work that requires an SSL key with a passphrase. If I try to push or pull using GitSavvy, it simply doesn't work instead of asking for the passphrase.

**Comment by stoivo** [comment]
What OS are you on?

**Comment by divmain** [comment]
Hi @atk.  There is no real fix for this on GitSavvy's side - Git provides no mechanism to 1) know when a password is required, or 2) pass a password to it.  However, you can use `ssh-agent` so that you are not prompted for your password, but everything remains secure.

Here are some relevant links that may help:

- [Working with SSH key passphrases (GitHub)](https://help.github.com/articles/working-with-ssh-key-passphrases/)
- [Configuring Git over SSH to login once (StackOverflow)](http://stackoverflow.com/questions/1595848/configuring-git-over-ssh-to-login-once)
- [How to tell git which private key to use (StackOverflow)](http://superuser.com/questions/232373/how-to-tell-git-which-private-key-to-use)
