### ISSUE TITLE
Suggestions for 'git rebase'

### ISSUE THREAD

**Issue by HughMacdonald** [divmain/GitSavvy#294]
Hi,

First off, I've just started using GitSavvy, and I do love it - it's great to be able to do everything from inside Sublime rather than jumping out to a terminal.

I generally do bits and pieces of rebasing, to keep commit trees tidy before putting in a Pull Request for a project. There are a handful of things that have come up with how GitSavvy handles rebases.

* Shifting a commit up or down by multiple commits takes time. Each move takes a second or so, and the cursor needs to be moved. I've got a couple of suggestions on this:
  * When a commit is moved up or down, automatically move the cursor so that it stays with the commit, rather than the line
  * Allow for a mode where the rebase isn't done every time a commit is moved, and can be triggered all at once at the user's discretion. Similar to how using `git rebase -i` would work.
  * Allow for selecting of multiple commits at once to move a block, rather than one at a time.
* When you `squash commit with next`, it seems to work in the opposite direction to `git rebase -i`, which squashes a commit with previous. It also uses the most recent commit for the commit metadata, rather than `git rebase` which (I think - I may be wrong about this) uses the oldest commit's metadata. I personally generally use fixup.

I'm definitely loving everything I can do with GitSavvy, but this is just the one area that I'm finding slows me down relative to how I worked before.

**Comment by divmain** [comment]
Hey there @HughMacdonald!  Thanks for the feedback.  I've been intending to revisit the rebase dashboard for some time now to add some polish.  But since the existing functionality addresses most of my daily pain-points, it hasn't happened yet.

A few thoughts:

- When making any change (not just moving), all commits shown will be re-applied to the tree.  This is often unnecessary, as really just the last commit or two may need to change, and it adds a significant performance hit.  Fixing this may alleviate much of the slow performance that you've experienced. Documented in #208.
- Moving the cursor to stay with the moved commit is a fantastic idea.  Opened #296.
- Queuing up actions is something I've considered, but could get very complex.  I have yet to come up with a clean way to do this that moves the heavy lifting over to Git.  Opened #297.
- Moving multiple commits is an interesting idea also,  In practice, I rarely perform actions on multiple things at a time (in the status dashboard, for example).  Is this something that you find yourself doing often?  This should be significantly easier to implement that the action-queue, so I've put it into that ticket as an alternative.
- With regard to the `squash commit with next`, would you mind opening a ticket with a fully fleshed-out example with repro steps.  Pretty sure I follow, but would like the problem to be clearly documented before attempting to address.

I'm unsure how much use the rebase dashboard truly gets across the userbase.  It is definitely something I use consistently, but issues aren't often reported, which is why many of these things haven't come up before.  Thanks again for the feedback!

**Comment by divmain** [comment]
And actually, since much of this was split out into other tickets, I'm going to go ahead and close this one.  Glad to continue discussion here, for anything not addressed in those smaller tickets, and please feel free to re-open if you think I've missed something.

**Comment by HughMacdonald** [comment]
Hi @divmain, thanks for all of that. I'll respond with my thoughts in the new issues, and open up a new one on the last point.
