### ISSUE TITLE
Add setting to allow signed commits instead of regular commits

### ISSUE THREAD

**Issue by TheHippo** [divmain/GitSavvy#36]
Add setting to allow signed and/or signed-off commits instead of "regular" commit.

**Comment by divmain** [comment]
@TheHippo, do envision this would be an additional palette command `git: commit (signed)`, or a global option where the flag would be included when set?

**Comment by p3lim** [comment]
Implementation suggestion; hold <kbd>Shift</kbd> when pressing <kbd>CTRL</kbd>+<kbd>Enter</kbd> when committing to also sign it.

**Comment by TheHippo** [comment]
There are two options for signing commits:

* `git commit -s` or `git commit --signoff` which adds just a text snippet to the commit message and seems to be implemented by @p3lim in #46 .
* `git commit -S` or `git commit --gpg-sign` which signs the commit with your GPG key.

Both options can be combined (`git commit -Ss`). In my opinion it would be the best option to have a "normal" commit command (`git: commit`) and a configurable signed commit command (`git: commit(signed)`) where your have to choose in a config file which signing options should be used.)

The GPG sign could be more complicated, since it might require unlocking your GPG agent / key ring.

Other then turning them on and off no other options are required, since GPG key and  message could be configured via the `git` command.

.

**Comment by p3lim** [comment]
> In my opinion it would be the best option to have a "normal" commit command (git: commit) and a configurable signed commit command (git: commit(signed)) where your have to choose in a config file which signing options should be used.)

What about having a separate commit command (`git: commit (signed)`) for GPG-signed, and also have my implementation in #46, so the user can mix and match between them (as you could with the porcelain).

**Comment by TheHippo** [comment]
@p3lim This sounds good.

**Comment by divmain** [comment]
Closing this also, since #68 seems to be blocked indefinitely.

**Comment by rpbaptist** [comment]
I looked into this and this can actually be solved outside of GitSavvy by simply configuring git globally or in your project. 

`git config (--global) commit.gpgsign true`

If you have a use case where you sometimes do and sometimes do not wish to sign your commits in the same project this won't help, but that's not something I am running into.

For more details: https://stackoverflow.com/questions/10161198/is-there-a-way-to-autosign-commits-in-git-with-a-gpg-key

**Comment by TheHippo** [comment]
@rpbaptist: This still doesn't solve the issue of unlocking you GPG key.

**Comment by rpbaptist** [comment]
You are right. I unlock it with my login keychain. I don't think it solves the full issue, but I was looking at this wanting to commit with GitSavvy and still be able to sign my commits. If my comment is irrelevant I can remove it.

**Comment by divmain** [comment]
Thanks @rpbaptist!  If you have a full workaround, would you mind enumerating the steps here or (even better) in a PR against the docs?

**Comment by rpbaptist** [comment]
@divmain 

Sorry for the late response.

I see the issue you linked has the same steps. I am not sure of `no-tty` is required in `gpg.conf` or not. I will find out when I reinstall my laptop. To get this to work I went through various settings, so I don't have a clear path.

For that reason I didn't make a PR to the docs yet.

But, I believe it would be something like this:

# Signing your commits with GPG

You can automatically sign your commits depending on your configuration.

## Add GPG key to GitHub and git

GitHub has instructions on [how to add your GPG key to GitHub](https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/) and [configure git to use your key](https://help.github.com/articles/telling-git-about-your-gpg-key/).

## Sign your commits automatically

If you always want to sign your commits you can configure git globally or in your project:

`git config (--global) commit.gpgsign true`

Now when you commit with GitSavvy, your commit will be automatically signed due to the git configuration.

## Unlock your GPG key

Next you want to tell git to ask for your passphrase through the gui. You can do this by setting the `askpass` variable:

`git config (--global) core.askpass git-gui--askpass`

I added my GPG to my keychain so it is unlocked when I log in as a user.

When you commit with GitSavvy it will attempt to sign your commit. If your key hasn't been unlocked yet with your passphrase you should now have a gui asking for it.

**Comment by divmain** [comment]
Sweet!  Thanks @rpbaptist.  I'm going to re-open this issue.  It'll be closed once this has been added to the docs.

**Comment by stoivo** [comment]
I created a commit which just adds this to the docs/commit.md

**Comment by divmain** [comment]
Thanks @stoivo!
