### ISSUE TITLE
Pull from status page

### ISSUE THREAD

**Issue by mreq** [divmain/GitSavvy#379]
Is there a reason for no git pull (potentially even a --rebase one) command in the status page? I can make a PR if you tell me the preferred keybind.

**Comment by stoivo** [comment]
There have been some discussion about it earlier but I can't recall, to you @divmain?

**Comment by divmain** [comment]
Yeah, we've discussed adding `pull` to the status page, and related discussions about what global palette commands to include.  The thing is, everybody has their own preferences about what should be available - some people use fetch really often, some people use a particular incantation of rebase, some people use pull, etc.

So we concluded that:

- Adding too many explicit key-bindings to the dashboards makes it cluttered and less useful.
- Therefore, status page should remain purely focused on the index (and stashes, since they were already there). (we have a "push current branch" command in the Status dashboard, but I'm honestly unsure of how it snuck in there)
- Sublime provides ways for users to customize their environment.  So:
    - People can add their own [custom palette commands](https://github.com/divmain/GitSavvy/blob/master/docs/custom.md) that are tweaked to suit their needs.
  - People can also add custom keybindings, although this isn't explicitly documented.  To do that, create a `Default.sublime-keymap` in the `User` directory, and add an entry like so:

```json
[
    {
        "keys": ["L"],
        "command": "gs_pull",
        "context": [
            { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "git-savvy.status meta.git-savvy.status.section meta.git-savvy.status.file" }
        ]
    }
]
```

**Comment by mreq** [comment]
Can't say I agree with that, as the UI is inconsistent now. I'd either remove the push keybind, or add a pull one. Also don't agree on a single keybind (a single line in the UI) cluttering the interface. I believe that pull/push/commit are the most common actions performed and that they all deserve a keybind in such an interface.

It's of course your decision, that matters. One can surely set custom keybinds/commands.

**Comment by divmain** [comment]
Totally understand, but I've exchanged almost identical words with other folks who have different opinions on what should be included.  I agree that adding a single line in the UI doesn't clutter - but adding several does.  At some point, all the keybinding hints just become noise.  I had to draw a line somewhere and "related to what we're showing you" seemed sane `¯\_(ツ)_/¯`

I'll think about removing the `push` keybinding from the status dashboard.  It is definitely an exception to the rule, and makes it unclear why we can't just add several more in there.

**Comment by IPWright83** [comment]
Is the status page configurable so that I can add it locally via some setting? I'd really like to do the same, but completely understand the desire to not do so.

**Comment by mreq** [comment]
@IPWright83 https://github.com/mreq/dotfiles/blob/master/subl/Packages/UserGit/Default.sublime-keymap#L44

**Comment by IPWright83** [comment]
@mreq Thanks! Took me a little while to figure out how to do it but got there in the end. For anyone else (Windows):

- Within Sublime `Preferences -> Browse Packages` 
- Go up a Directory and into `Installed Packages`
- Copy `GitSavvy.sublime-package` somewhere else
- Rename the copy `GitSavvy.sublime-package.zip` and open it up.
- Look for the `Default.sublime-keymap` file and Edit it (probably need to take out the zip first).

At this point I used the following (decided to not do a rebase)

```
   {
        "keys": ["g"],
        "command": "gs_custom",
        "args": {
            "args": ["pull"],
            "output_to_panel": true,
            "start_msg": "Starting pull",
            "complete_msg": "Pull complete.",
        },
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true },
        ]
    },
```

- Update your zip file
- Remove the `.zip` extension
- Replace the `gitsavvy.sublime-package` with your modified one
- Restart Sublime

**Comment by mreq** [comment]
Hey, even better (so that you still get updates) - just add the code you did inside of your keymaps - `Ctrl+Shift+P` > `Preferences: Key Bindings`.
