### ISSUE TITLE
Fetch required after git remote add

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#390]
1. Add remote
2. Git Pull
3. Select the name of the remote
4. [Nothing happens - branches within the remote are not presented]
5. Git Fetch
6. Select the name of the remote
7. [Now branches are presented in a list]

**Comment by stoivo** [comment]
What is it you would like to have? Is this what you want?
1. Add remote (GitSavvy does fetch that remote)
2. Git Pull
3. Select the name of the remote
4. Select the name of the branch

**Comment by stevage** [comment]
Yeah. So for some reason GitSavvy isn't fetching the new remote for me and it should?

**Comment by divmain** [comment]
Right now, all that `git: add remote` does is `git remote add NAME URI`.  If you were to do this on the command line, a fetch would be necessary.

However, since most times you would want to fetch after adding, I don't see a problem with asking the user `Would you like to fetch history from your new remote?`.  Does that seem like a reasonable direction for resolution of this ticket?

**Comment by stevage** [comment]
Well I'd ask the question: when does the user *not* want to fetch after adding the remote? Imho never. So why bother with the question?

**Comment by stoivo** [comment]
@stevage because adding remotes is SWAG... :P
I agree with you @stevage, I can not think of an scenario where I don't want to fetch after adding a remote. I would try not to add more setting that make sense.

**Comment by divmain** [comment]
Sorry to let this conversation drop.  To answer your question, I sometimes add a remote so that I can push a branch, but I don't necessarily want to pull down all their commit history.  In the case of big repos, this can be a lengthy process.  So we should at least gate it with a prompt.

**Comment by stoivo** [comment]
👍  for a prompt.
