### ISSUE TITLE
configure tracking in the branches dashboard no longer works

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#391]
When I try to configure tracking, I get this error:
> Traceback (most recent call last):
  File "core.interfaces.branch in /Users/<user>/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 349, in run_async
AttributeError: 'GsBranchesConfigureTrackingCommand' object has no attribute 'get_remote_branches'

I haven't looked at exactly when this started failing, but it must have been fairly recent.

**Comment by stoivo** [comment]
Strange.
I can see passed on the path that you are using OSC and ST3. It looks like you installed GitSavvy form Package manager, is that correct?  
Can you check which version of Sublime you have? 

This happens when you open branch dashboard and press `t`? Just we are looking at the same feature :)

**Comment by allen-zeng** [comment]
Sure :)

This happens when I open the branch dashboard and I press `t` on a line that displays a local branch. It doesn't matter which local branch it is either.

I did install GitSavvy from Package Manager. I can also confirm that the `GitSavvy` folder under `Packages/User` only contain `tmTheme` files.

My Sublime version is Dev 3111.

**Comment by allen-zeng** [comment]
I think the problem just resolved itself - I had to restart Sublime.

This is very strange indeed :/

Thanks for your time anyway!
