### ISSUE TITLE
Don't add "# added by GitSavvy" to .gitignore files

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#393]
I'm not sure what the thinking behind this line being added is. It basically makes the "ignore" feature useless for me. For any shared project it's not very friendly to have comments like this dotted around, so I end up having to remove them manually...

**Comment by divmain** [comment]
This was one of the original features and, at the time, I was concerned about ways that GitSavvy could do damage to a person's work.  Adding the comment served as a big fat warning label.  However, nobody has expressed concerns about it since, and it has turned out to be pretty reliable.  So we'll make this change!

**Comment by stevage** [comment]
Cheers. And if you're anything like me, you're committing everything in hunks anyway, so you'll see the change before it gets committed.

(Have I mentioned that this is one of the best things about GitSavvy for me - checking every single hunk before it gets committed is so easy that it becomes a very natural part of the workflow. It's awesome.)

**Comment by stoivo** [comment]
Should we add  
1. `\n<pattern>`
or 
2. `<pattern>\n`
or to be super safe but then the .ignore file looks supit
3. `\n<pattern>\n`

I always leave an empty line at the end. I am not sure what's more common. So 2. option is my goto.

**Comment by stoivo** [comment]
Or maybe 3th is better since most of the time when you ignore a pattern you want to have a comment with why this pattern should be ignored.
