### ISSUE TITLE
CRITICAL: changes get lost when making live rebase

### ISSUE THREAD

**Issue by old9** [divmain/GitSavvy#409]
WARNING: create a sandboxed repo to test these:

1. Say I'm now on ref 8d19112
2. I have 3 files changed, file1, file2, file3
3. add file1, commit
4. add file2, commit
5. leave file3 unstaged and enter live rebase dashboard
6. press r to rebase on top of ref 8d19112
7. Sublime warns me that `Cannot rebase: You have unstaged changes. Please commit or stash them.`
8. I didn't notice that warning and pressed u to move a commit up(or move down, or squash, whatever)
9. boom, changes to file3 are lost FOREVER

**Comment by old9** [comment]
I'm creating this issue with tears in my eyes, seriously.

**Comment by divmain** [comment]
Hey @old9, I'm very sorry and I'll look at this later today.

However, if these changes are important to you, take a look at the diffs for the top commit that was rebased with you "move up" action.  It is possible that the unstaged changes were rolled into that diff and are not lost.  Under the hood, GitSavvy is doing `git cherry-pick` and `git cherry-pick --no-commit`, so that seems likely to me.  Even if you've done work since then, you may be able to recover by walking back through your ref log.

That said, this is definitely a bug, and I'll push out a fix ASAP.

**Comment by divmain** [comment]
@old9, I hope you were able to recover the work.  I've added a change to disallow any actions in the rebase dashboard when the repo is in an unclean state.

**Comment by old9** [comment]
Thanks, I'll try that ASAP when the update is available on the package control.
Since not that much of the lost work, I've recovered them manually already.
