### ISSUE TITLE
Awesome but drab User Interface in git diff view

### ISSUE THREAD

**Issue by andela-mpitan** [divmain/GitSavvy#416]
Hello,
1) I hope by now you don't need anyone to tell you what great job you are doing on Git Savvy.
2) I am personally wowed. I am a person that has an affinity for beautiful UI however.
3) The `git: diff` view is great but I will appreciate if it could display with colours just as the `git diff inline` view as opposed to the `++` and `-- `signs that depicts additions and deletions currently.

**Comment by stoivo** [comment]
I not sure what you want. Would you explain some more what you want?

**Comment by andela-mpitan** [comment]
Sorry for the unclear request
What I am basically asking for is a `git diff inline` page for all files. There is currently a `git diff inline` page for just one file, I would appreciate if it could be extended to more than one file

**Comment by stoivo** [comment]
ov, now I understand you question.

That sound cool but it will we very hard to make, since it the inline diff have syntax highlighting for syntax it is. This can be done but complicated. The inline diff is quite complicated already. 

Would it help so have `s` for switch files. Then open a panel with fuzzy find and switch files like that?

**Comment by divmain** [comment]
As @stoivo mentioned, creating the equivalent of the inline diff view for an entire working directory is very difficult.  Because of that, we've decided to instead focus on adding features for navigating between files and dashboards.  This provides most of the convenience you'd get with the monolithic inline diff view, while keeping complexity low(er).

Going to close this issue.  But if you have specific thoughts or requests that fit within that scope, please feel free to re-open or create a new issue.

**Comment by andela-mpitan** [comment]
Sorry for getting back to you guys late. The normal git diff view for all files is actually colourful on my sublime with the help of Material Theme. The theme I was using before did not just use colours for that view for reasons best known to it. I enjoy GitSavvy's diff view now. Thanks for your concern, though.

**Comment by divmain** [comment]
:+1:  We're also looking at adding integrated themes as part of GitSavvy, that would just apply to GitSavvy views.  Keep an eye out - that may improve your experience further.
