### ISSUE TITLE
Diff with branch

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#417]
How can I diff a file with a version on a particular branch (say master)

equivalent git command: `git diff current-branch master -- /path/to/file`

**Comment by stoivo** [comment]
What I would do is 

1. Open branch dashboard
2. Find the branch you want to compare to active branch.
3. Press `f` to open the full diff between the branches.
4. Open the do to symbol `control + r ` (or `command + r ` on OSX).
5. Fuzzy find the file you want to see.

If you follow these steps I think you will find the result you are looking after.

**Comment by stoivo** [comment]
@dufferzafar, is this what you where looking for?

**Comment by dufferzafar** [comment]
Not exactly, no. I tried this, and it only displays the differences that have already been committed, and not the dirty stuff.

**Comment by stoivo** [comment]
I did some testing and it shows up that if I do `git diff current-branch master -- /path/to/file` it only show that committed stuff, since this compares the last commit on the last commit current-branch with on master. If I do `git diff current-branch -- /path/to/file` it will compare master to working tree. So is that what you are looking for?

**Comment by dufferzafar** [comment]
Yeah, i think so :/

**Comment by stoivo** [comment]
Can you explain when you would use this?

**Comment by divmain** [comment]
Closing.  Feel free to re-open or open a new issue if there's something that needs to be addressed.
