### ISSUE TITLE
Support hub commands?

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#435]
[`hub`](https://github.com/github/hub) is this insanely useful tool that adds github specific commands like `fork`, `pull-request` etc. 

I primarily use it to create PRs from the cli, and this is the only reason I even switch to my terminal for doing git related things. [I just use GitSavvy for everything else.]

It'd be really great if we could have support for hub commands (especiall `pull-request`) in Savvy!

**Comment by stoivo** [comment]
There is some work started on [this(GitSavvy/issues#364)](https://github.com/divmain/GitSavvy/issues/364). 

I think this would be nice to have in a separate package since there is many git server not related to github.com in any way.

Thanks for opening issue.

**Comment by divmain** [comment]
Yeah, I think this will hard to support well, since `hub` is a moving target, whereas most of the Git commands we rely on have been present for several years.  It'd probably be easier, honestly, to port the features to GitSavvy directly.  We do have some minimal support for PRs.

If there are specific features that you find yourself going to the terminal to run, open a narrower issue (or PR!) describing the workflow and what you're trying to accomplish.
