### ISSUE TITLE
Cursor movement in dashboards

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#453]
Currently, only the status dashboard has support for cursor movement with the keyboard, it would be nice if all of the dashboards had support for this.

**Comment by stoivo** [comment]
I think this is fixed in on master but it's a long time since last release.
It was implemented in https://github.com/divmain/GitSavvy/commit/c717e4a56ae35d8eff35db8d93a629c5106b27a7 https://github.com/divmain/GitSavvy/commit/86eac9941595a49f87597d38234585b51cdb290f https://github.com/divmain/GitSavvy/commit/e13585e7e3a36ef4b3fa6a4b9140e8e984884e7d https://github.com/divmain/GitSavvy/commit/b489b670a23a4c43564a80f4a73ab76e5016fb4d

**Comment by p3lim** [comment]
Yup, been some time since there was a release :/

**Comment by divmain** [comment]
I pushed out a release - sorry for the delay!
