### ISSUE TITLE
Git Binary not found

### ISSUE THREAD

**Issue by skeptikokyy** [divmain/GitSavvy#478]
Hi all,

I am new to the git world and I have been coding only a few months and I wanted to optimise my performance by using Gitsavvy and when I installed it I got a message shown in the image below everytime i try do something. I have tried to add path in Variable env to no success. Doesanyone know I resolve this? Thank you.
![gitsavvy](https://cloud.githubusercontent.com/assets/13117682/17258271/59a0ae9e-55c6-11e6-9c8e-9faf3cc6628b.JPG)

**Comment by stoivo** [comment]
Does git work from command line?

How did you install git? 

That is the output when you run `which git` in cmd?

**Comment by divmain** [comment]
Hey @skeptikokyy.  GitSavvy can't find your `git` binary.  If adding to your PATH doesn't work, sometimes that means that Sublime is running in a different process environment than the one that you're configuring.  This can be for a number of reasons, and isn't always easy to resolve since it is really situational.

The best thing to do would be to:
- Identify the absolute path to your `git` binary.
- In Sublime, open the command palette and type `GitSavvy Settings - User`.
- This is a JSON file, and if you don't alreayd have anything in here, you should add this block:
```json
{

}
```
- Add the following entry, obviously replacing the value with the Git path you identified earlier:
```json
    "git_path": "PATH_TO_GIT",
```

If that doesn't work, please reach out to us on Gitter and we can help resolve from there: [link](https://gitter.im/divmain/GitSavvy).
