### ISSUE TITLE
More informative commit view

### ISSUE THREAD

**Issue by yetithefoot** [divmain/GitSavvy#488]
When im writing commit message I prefer to see changes that will be commited and branch info.

Now it looks like:
<img width="794" alt="screenshot 2016-08-04 17 51 19" src="https://cloud.githubusercontent.com/assets/699027/17406453/1870e844-5a6c-11e6-8da3-7aef85f4ecb9.png">

But view like this looks more informative:
<img width="698" alt="screenshot 2016-08-04 17 51 28" src="https://cloud.githubusercontent.com/assets/699027/17406460/2404cc3e-5a6c-11e6-90a9-90c02984d514.png">

Suggest extend commit view with extra information

**Comment by divmain** [comment]
Would [this option](https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L48-L52) suffice?

**Comment by aziz** [comment]
I think full diff is too much I also like to see a summary of things that are being commited.

**Comment by yetithefoot** [comment]
@divmain Not really. As @aziz mentionned, its too much.
Probably smth like this would cover most of possible scenarios:
```
{
    "show_commit_diff": "full", // full changes
    "show_commit_diff": "filenames", // only filenames
    "show_commit_diff": "none" // nothing
}
```
In my cases filenames is enough.

**Comment by divmain** [comment]
In #492, @tomngo asked for previous commit messages, since commit messages will often be similar.  Let's come up with all the possible bits of information we might want in the commit view, and then expose a config option to allow people to set this up granularly.

One way would be to just accept a raw `git` command.  You could pretty simply craft one to show previous commit subjects, or show a full diff, or show filenames that have changed.  We could also accept an array of these, for people that want lots of info and don't want to choose between them.

However, this would be more heavy-handed, and exposing more constrained but popular choices as boolean options might be better.

Thoughts?

**Comment by tomngo** [comment]
Thanks! For convenience, I'd prefer the more constrained but popular choices. If there were a way to enhance by adding raw `git` commands to user preferences, I'd likely use that.

**Comment by rchl** [comment]
I'd really like this improvement. One thing that wasn't mentioned is showing the branch we are on. I'd like that too.

**Comment by rchl** [comment]
Ability to select previous commit messages would also sort-of solve #503.

**Comment by asfaltboy** [comment]
@tomngo could you elaborate on what you mean by "'enhancing by adding raw `git` commands" ? 

Today, you could either enhance specific GitSavvy commands with [custom arguments globally][1], or [define a custom command][2] to do your specialized work.

Please let us know if this is satisfactory, and whether there's anything else you're looking for.

[1]: https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L132
[2]: https://github.com/divmain/GitSavvy/blob/master/docs/custom.md

**Comment by tomngo** [comment]
@asfaltboy : My comment was a response to @divmain 's question on the same day (Aug 10). I think your "define a custom command" response already satisfies the need. Thanks!

**Comment by yetithefoot** [comment]
Thanx
