### ISSUE TITLE
git:diff - adding --patience option

### ISSUE THREAD

**Issue by stdedos** [divmain/GitSavvy#509]
Hello! I am used to work with `--patience` option, because many times it produces an easier to read diff.

Is there any way I can add this to all the diff operations executed?

**Comment by p3lim** [comment]
Take a look at this: https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L128-L136
No idea if it interferes with how GitSavvy works though.

**Comment by stdedos** [comment]
I guess "global" is a bad thing to do in the first place, that's why I opened an issue - to get an "authority" answer if/how it can be done

**Comment by stoivo** [comment]
I dont think there is a way to add this currently. I might have time this week to look at it. I have to re which issues I will that have the highest priority.

**Comment by stdedos** [comment]
(y) I understand that's a low-prio.
I'd appreciate if you did though :)

**Comment by asfaltboy** [comment]
@stdedos if you could kindly clarify what you expect from this feature that is not provided by "global_flags"? There is nothing inherently wrong with using this setting.

In other words, if you _always_ include this flag, simply edit your GitSavvy User settings to include:

    "global_flags": {
        "diff": ["--patience"]
    }

Otherwise, we'd appreciate if you could describe your optimal expected solution.

related to #430

**Comment by stdedos** [comment]
Oh! My bad in reading the settings. File. Thank you for the reference though, it cleaned up my head.

I thought it would also look like, eg: git log --patience "the rest"
