### ISSUE TITLE
Discarding staged files is not possible

### ISSUE THREAD

**Issue by iamolivinius** [divmain/GitSavvy#57]
In the status view I'm not able to discard staged files with the `d`-key. For unstaged files this works perfectly.

**Comment by divmain** [comment]
This was intentional - discarding a staged file seems ambiguous, especially if that file is partially staged.

For example, let's say half of `file.ext` is staged, I select `file.ext` in the unstaged section, and then I hit `d`.  The outcome would be as expected - the staged portion would remain staged, and the file in the working directory would revert to HEAD.  `file.ext` in the index would be unchanged.

However, if instead I select `file.ext` in the staged section and hit `d`, the outcome is not clear.  Would the file be unstaged?  It would have to be, if the action did anything.  But it would have to do more than simply unstage, so it would perhaps unstage and then revert the file in the working directory to HEAD.  However, in that scenario, the action taken effects the file both in the index and in the working directory, which (in my mind) is not the expected outcome of selecting the file in the index and performing an action.

I'm open to discussing it, however - so if you have additional thoughts or ideas of what `d` should do to staged files, please let me know.
