### ISSUE TITLE
Signing fails via GPG

### ISSUE THREAD

**Issue by jrappen** [divmain/GitSavvy#581]
I started [ST3](https://www.sublimetext.com/3) with the GitSavvy (`v2.13.0`) plug-in via [cmder](https://github.com/cmderdev/cmder) to run a signed `git commit`. Signing fails with the following error in the GitSavvy output panel:

```text
`%CMDER_ROOT%\vendor\git-for-windows\cmd\git.EXE commit -q -F -` failed with following output:

gpg: cannot open tty `no tty': No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```

* Using cmder directly works as intended.
* I wasn't prompted for a password by GitSavvy while attempting to sign.

**Comment by randy3k** [comment]
You may need to cache your github password, check https://help.github.com/articles/caching-your-github-password-in-git/#platform-windows

I will let the more experienced Windows users answer this issue.

**Comment by stoivo** [comment]
Can make a log with GitSavvy 
https://github.com/divmain/GitSavvy/blob/master/docs/debug.md

**Comment by asfaltboy** [comment]
I think this isn't related to github, issue #36 discusses signing commits, and how to enable them via a global config.

As far as I know, there isn't a clean way to sign with a password protected key.

**Comment by jrappen** [comment]
@asfaltboy as I implied above by mention the lack of a prompt for the password, the key is protected.

**Comment by jrappen** [comment]
@randy3k @asfaltboy I'm not intending to cache my password.

**Comment by asfaltboy** [comment]
I'm sorry @jrappen , but password prompts are not currently supported.

**Comment by jrappen** [comment]
Would it be possible to prompt via an input panel within Sublime similar to when renaming files and then passing the input through?

**Comment by jrappen** [comment]
@asfaltboy My `~/.gitconfig` has `core.editor = subl`, `user.signingkey = ...` and `commit.gpgsign = true`. Usually I would do a `git commit` from [cmder](https://github.com/cmderdev/cmder), which opens ST3 to write the message. Closing the window there, makes cmder continue to prompt me for the password to gpg sign my git commit and if successful do my signed commit.

**Comment by asfaltboy** [comment]
We can ask for the passphrase, but the issue is communicating that input to GPG securely. As a workaround, I suggest leaving sublime out of the passphrase step, and use `pinentry.exe` (installed with gpg4win) for this step.

Start by making pinentry dialog for passphrase work from command line commit (e.g `git commit -m "test"`, without sublime text) with following this guide:  https://jamesmckay.net/2016/02/signing-git-commits-with-gpg-on-windows/ . Once this works well, I imagine you should be able to enter your commit message in ST and get the pinentry dialog for the passphrase.

**Comment by divmain** [comment]
As @asfaltboy mentioned, it is prohibitively difficult to support dynamic interactions with Git from within Sublime.  This is largely due to the way we interact with subprocesses in Python and the constraints of Sublime itself.  Since a work-around has been provided, I'm going to mark this as closed.  Sorry if this isn't the answer you were looking for!

**Comment by BoGnY** [comment]
If needed, [this is my gist](https://gist.github.com/BoGnY/f9b1be6393234537c3e247f33e74094a) that explain how to enable auto-signing of Git commits for **EVERY** programs that don't support it natively..
It's specifically for Windows systems and solve this problem!!

**Comment by jrappen** [comment]
@BoGnY Looking through your post, I suppose most people will only be missing `$ git config --global gpg.program "/c/Program Files (x86)/GnuPG/bin/gpg.exe"` from their current setup.

**Comment by BoGnY** [comment]
@jrappen Also `$ echo 'no-tty' >> ~/.gnupg/gpg.conf` which is the first problem of this issue.. 
In some case is mandatory, and not an optional...

However, `gpg.program` setting must be path of your local installation of GnuPG, latest is 2.2.4...
It can be any other program that supports GnuPG, but must accept via command line the same arguments of *nix native gpg program!!

Finally, `gpg.program` setting must be written like this `"/c/Program Files (x86)/GnuPG/bin/gpg.exe"`, I have not found any other compatible, i tried `"C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe"` and `"\"C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe\""`...
But in first case, git configuration remove double quotes, so the setting becomes `C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe` and gpg sign fails due to the presence of spaces in the path, in second case setting becames `\"C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe\"` and fails again due to the presence of backslash in path...

So I came to the conclusion that, or you use this *nix style configuration:
```shell
$ git config --global gpg.program "/c/Program Files (x86)/GnuPG/bin/gpg.exe"
```
Or you manually put in your ~/.gitconfig file this win style configuration:
```ini
[gpg]
    program = "C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe"
```

:thumbsup: :smile:
