### ISSUE TITLE
Feature Request: Add support for patch stashing

### ISSUE THREAD

**Issue by Drllap** [divmain/GitSavvy#595]
I would love to be able to do this [so link](http://stackoverflow.com/a/17969785) without having to open up a console window.

Note that it is possible to name the stash if you use this command: git stash save --patch "stash name"

**Comment by stoivo** [comment]
Have you seen inline diff?  
https://github.com/divmain/GitSavvy#highlights
https://github.com/divmain/GitSavvy/blob/master/docs/staging.md#git-diff-current-file-inline

It does the same job with a different interface.

**Comment by Drllap** [comment]
I have, and use it all the time. But can you create a stash with it?

**Comment by stoivo** [comment]
No. I have read it wrong. This is a difficult to implement with our current code since out code it make to handle prompts from commands. 

Since everything we do in GitSavvy calls git it is hard to replace who git command should work.  There are other command which would have benefit of this change.

**Comment by stoivo** [comment]
Not saying it is impossible but I won't work on it. For now atleast.

**Comment by divmain** [comment]
Hey @Drllap, this is a feature I've been wanting myself, for awhile now.  I just pushed a commit that may not be exactly what you ask for, but close enough.  There's a new command in the status dashboard: `[t][g] create stash of staged changes only`.

Go through your normal workflow to stage files - inline diff views should work for this.  When you're ready, press `[t][g]` in the status dashboard and _only_ the changes you have staged will be added to a stash and removed from your working directory.

It will not work in 100% of cases.  One example where it would fail, is if you stage lines in the middle of a hunk and Git is unable to reverse-apply the patch because necessary context is missing.  In this case, the stash will be present, but the changes will not be removed from the working directory.

I might be able to improve this if I can figure a way to diff two stashed-diffs and generate a diff-diff :) . But this is good enough for me right now.  Let me know how it works for you.

**Comment by Drllap** [comment]
Haven't tested it yet but sounds like it's exactly what I was looking for.

Those corner cases you talk about here it doesn't work sound very minor, especially when one know about them.

Thx a lot for your effort.

**Comment by alextegelid** [comment]
Nice one @divmain and thanks for the request @Drllap ! This will improve my workflow significantly since I've just recently started using stashes frequently
