### ISSUE TITLE
Erratic behavior of stash commands in git: status

### ISSUE THREAD

**Issue by tailsu** [divmain/GitSavvy#600]
Disabled stash commands should be marked as such in the help. Pressing [t][a] when that command is actually not available does an [a] - stage all files. And there's no indication that pressing [t][a] will do something else entirely. I also think that pressing [t][a] should be a noop when the command doesn't make sense - and not disregard the initial [t]. Ideally, I think, pressing [t] should change the help text to show that "you're in stash mode", for example, by replacing the entire help text with just the help text of the stash commands for the duration of the command (without triggering a status refresh, that would be annoying).

**Comment by stoivo** [comment]
I dont think it is possible. 
Since the command looks like 
https://github.com/stoivo/GitSavvy/blob/7a064d629b8bfd37fb7ee5fa4fe0f4fb5486c314/Default.sublime-keymap#L292-L300

It is either triggered or not. I don't think there is a intermediate state.  If you have an idea of how to do it, I am open.

The other think is that I need to look at the the complexity/benefit of the code which would need to change.

**Comment by tailsu** [comment]
I think you could fix the first issue - that pressing [t][a] triggers [a], by simply removing [the context check](https://github.com/stoivo/GitSavvy/blob/7a064d629b8bfd37fb7ee5fa4fe0f4fb5486c314/Default.sublime-keymap#L298) and doing the check inside the command instead, doing a no-op when the command doesn't make sense.

The "stash mode" is just nice to have, I guess, but not really necessary. The idea is to split the stash shortcuts into [t] - "enter stash mode" and [a], [p], etc., that are the actual stash command but are enabled only if you're in stash mode. All other key presses take you out of stash mode. As I describe it, it seems really not worth the effort :smirk_cat:

**Comment by divmain** [comment]
Yeah, I see what you're getting at, and I'm sure it was irritating.  But since any destructive action will result in a prompt, and anything else is recoverable, this seems like there's very minimal risk involved.  And unfortunately, the pure-text Sublime environment and its APIs place certain constraints on the dynamism of the view.

This is an interesting idea, but as you say, perhaps not worth the effort.  I'm going to close the issue for now, but please feel free to re-open or just post if you have other thoughts or ideas.  Thanks for filing the issue!

**Comment by tailsu** [comment]
I'd still like to have the first part of the fix:

> I think you could fix the first issue - that pressing [t][a] triggers [a], by simply removing the context check and doing the check inside the command instead, doing a no-op when the command doesn't make sense.

**Comment by divmain** [comment]
Hmm that's fair.  OK, I'll re-open until thats implemented.

**Comment by tailsu** [comment]
You guys are the best :) I could just wish that guys as awesome as you were working on Sublime's TypeScript support or SublimeCodeIntel.

Kisses!

**Comment by stoivo** [comment]
Thanks @tailsu, Good to hear.
