### ISSUE TITLE
[Question] __init__.py is not required in package root.

### ISSUE THREAD

**Issue by deathaxe** [divmain/GitSavvy#626]
I have a kind question just for my own interest. 

Why do you add an `__init__.py` to package root? None of the default packages do that and there seems absolutely no drawback when removing it.

It is very fine to use it to "merge" all files in the sub directories to one package, but as far as I know, it doesn't make sense in the package root. It is explicitly loaded by ST just like a normal python file but without any functionality.

The suggestions discussed [here](https://github.com/sublimehq/Packages/issues/32) don't use it, too, even though all python modules are placed in a `src` sub directory.

I guess the git_savvy.py is the only needed python file in the root.

**Comment by stoivo** [comment]
This is the commit message
```
Other: convert directories with code to proper packages
Add __init__ module to all directories with python modules.

This is mainly to make the relative improts make sense for my
anaconda/jedi when running goto/autocomplete commands.

I assume this would help us when we write unit tests as well
```

**Comment by deathaxe** [comment]
Yes this is absolutely, correct with all the sub directories. This makes python see all modules in the directories as they were merged in one file on `import`.

But I was just wondering, whether it is required for package root, too, as all the files there are explicitly loaded by `importlib.import_module()` (see _sublime_plugin.py_). ST3 does not import the package root folder as normal python package. It in fact creates a package for each root folder explicitly, even without `__init__.py` in it.

A `print(__package__)` statement in a file located in the package root outputs the directory name (GitSavvy or GitGutter in my case). This works without `__init__.py`, too. 

Same with unit testing. I have the UnitTesting package installed. It is used in GitGutter for the promise module. It works with or without `__init__.py`.

Your reload module and the _Automatic Package Reloader_ plugin recognize packages without __init__.py, too.

On the opposite, ST3 explicitly loads __init__.py as it was a normal module implementing some normal functions.

All those facts make me wonder, what's the sense of this file as it obviously does not have any function or meaning in this special case.

So I assume it is not required and won't add such a file to GitGutter. This was the reason for my question.

Thanks.

**Comment by asfaltboy** [comment]
The `__init__.py` in root is only required if you need to reference the "root" package from sub-packages.

For example in [`core/git_command.py` we do:][1]

    from ..common import util

Without the `__init__.py` file the import would not be possible (outside of sublime) since the import function cannot "descend" to a directory outside of root package (top-most dir with `__init__.py`).

To clarify what I meant in the commit, the use cases for this structure are for following imports **outside of sublime**, i.e without it the below would not be possible:

- Using helper plugins: Anaconda -> Goto Definition
- Running an external test runner: Run unittest directly from OS (for non-sublime related functionality if such exists)

If that answers your question @deathaxe , please go ahead and close the issue.

[1]: https://github.com/divmain/GitSavvy/blob/master/core/git_command.py#L15

**Comment by deathaxe** [comment]
Ok, thanks for your answer. Never took into account, that you use some modules directly in python without ST. So I won't need such a file as ST3 always creates a package from the root directory.
