### ISSUE TITLE
Use ST window command open_url

### ISSUE THREAD

**Issue by jrappen** [divmain/GitSavvy#629]
Instead of importing `webbrowser.open` you can use:

```python
import sublime

# ...
    sublime.active_window().run_command('open_url', { 'url': 'https://www.sublimetext.com' } )
```

**Comment by asfaltboy** [comment]
Hi @jrappen thank you for submitting the issue!

Could you please add a bit more details on why using the built-in command is better than the current implementation? Does this fix some issue for you?

The reason I ask is that the current implementation is "stable" and not dependant on ST's implementation. Since the built-in commands are not officially documented (AFAIK, the only reference I found is in the [unofficial docs][1]), the command `open_url` or it's syntax may experience potential (breaking) changes in the future.

I have also found [a reference to potential issues with using the `open_url` command][2]. It seems that the command does not use the default browser (at least in some environments).

[1]: http://docs.sublimetext.info/en/latest/reference/commands.html?highlight=open_url
[2]: https://forum.sublimetext.com/t/how-does-the-open-url-command-select-the-browser-to-use/21590

**Comment by jrappen** [comment]
I'm not experiencing any issues. `webbrowser.open` works fine for me.

I assumed reducing the amount of imports would help.

**Comment by jrappen** [comment]
Reference: SublimeTextIssues/Core#1280
