### ISSUE TITLE
git graph uses wrong encoding

### ISSUE THREAD

**Issue by 3v1n0** [divmain/GitSavvy#668]
As you can see in this screenshot:

![image](https://user-images.githubusercontent.com/345675/27107084-887e5628-5096-11e7-90d9-8633d8b441c8.png)

When using `git: graph` in my branch, the encoding is wrong for the view.
Quick panel uses proper one instead.

**Comment by stoivo** [comment]
Can you create a demo repo?

**Comment by 3v1n0** [comment]
`git clone https://github.com/3v1n0/mutter -b wip/resource-scale`

Using this in a new sublime-text linux installation (with just Package Config and GitSavvy) generates such `git: graph)

**Comment by stoivo** [comment]
The problem is that GitSavvy decodes the how output from `git log ...`.  
In d71ef42dedbd992b500285a7ed87bf29029cedd3 there is a commit message which is not valid utf-8 so er tried to decode with latin1 and it worked. 

You should each fix that commit or as I would recommand, you can set your oun git_graph_args like 
```
	"git_graph_args":
	[
		"log",
		"--pretty=format:%h%d %s (%ar) <%an>",
		"--graph",
		"--no-color",
		"-20000"
	],
```
Which limit your graph to  20 000 commit which I guess is enought. 

Feel free to reopen.

**Comment by 3v1n0** [comment]
Mh, I see... But why applying this rule to all the subsequent commits?

As they would fail anyway...

**Comment by stoivo** [comment]
We are not decoding each line of the commit. We are decoding the whole block we get from `git log --pretty='format:%h%d %s (%ar) <%an>' --graph --no-color`. If we did split it by new line and decoded each line, that would have worked more correct, but that's too expensive

**Comment by stoivo** [comment]
If you hit `m` to show details about the commit and then navigate with `,` and `.` it displays correctly.

**Comment by 3v1n0** [comment]
Yeah, in fact that works... Mh.. I see the problem.
