### ISSUE TITLE
github: review pull request

### ISSUE THREAD

**Issue by kylebebak** [divmain/GitSavvy#691]
Executing this command doesn't seem to do anything, except print this to the console:

`Error querying github: {'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}`

Creating a pull request works just fine =)

**Comment by randy3k** [comment]
It is still working for me. Could you try running it again? May be a network issue.

**Comment by kylebebak** [comment]
Hey @randy3k , sorry I didn't get back to you sooner. It's still not working for me, it's definitely not an issue with my connection.

This is the traceback printed to the ST console:

```
1 problem 
Traceback (most recent call last):
  File "github.commands.pull_request in /Users/kylebebak/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 39, in run_async
  File "github.github in /Users/kylebebak/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 139, in query_github
GitSavvy.core.exceptions.FailedGithubRequest: Error querying github: {'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}
```

**Comment by asfaltboy** [comment]
Please provide more information, at the very least, what is your repository address

**Comment by kylebebak** [comment]
@asfaltboy I'm running ST build 3141 on OSX. I'm trying to do this with a private repo to which I have read and write access via SSH keys. Maybe that's the problem.

**Comment by randy3k** [comment]
Ya, the github api is used to access github data. You will need to specific an API token in GitSavvy settings.

**Comment by asfaltboy** [comment]
@kylebebak this is explained in [the Github integration documentation][1]

Please let us know if this still fails, and/or how the documentation can be improved.

@randy3k we could probably catch this `'message': 'Not Found'` error and provide a more friendly error message?

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/github.md#setup

**Comment by kylebebak** [comment]
@randy3k @asfaltboy 

Awesome guys, I'll get this set up. Thanks a bunch =)

**Comment by randy3k** [comment]
We should definitely catch the error. But it can be caused by many reasons, not sure what the best way to prepare the message.

**Comment by divmain** [comment]
Agreed - this is an unfortunate limitation of integrating with the GitHub API.  For obvious reasons, they don't want to tell us "the information you provided for authentication doesn't work for this repository".  They don't even want to leak that a repo even exists to folks that don't have access.  So this could be caused by forgetting to enter the auth key, typing it wrong, typing the repo wrong, or any number of other things.

That being the case, I don't consider this really fixable.  If you can think of a way we can call this out better in the docs, we'll be happy to make the change!
