### ISSUE TITLE
Error upon updating to v2.14.9

### ISSUE THREAD

**Issue by jrappen** [divmain/GitSavvy#704]
```text
Package Control: Upgraded GitSavvy to 2.14.9
Traceback (most recent call last):
  File "...\sublime3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in ...\sublime3\Data\Installed Packages\GitSavvy.sublime-package
```

* Win 10 Pro x64
* ST3 Build 3141 (x64, portable)

---

Above is the console printout from Sublime. Sublime reloaded the package after that automatically and everything worked fine.

**Comment by divmain** [comment]
Hmm... that's strange, and definitely a Sublime bug.  The `.zip` files are automatically generated by the Package Control backend - it might be an issue with that, or with the Sublime version that you're using. 
 Since it reloaded automatically without issue, and since this is not something I can directly address anyway, I'm going to close this as `won't fix`.

**Comment by jrappen** [comment]
Fair enough.

FYI the error keeeps showing up every time Sublime starts up...but you knew that.

/cc @wbond

**Comment by wbond** [comment]
@jrappen Have you inspected that `.sublime-package` file to see if there is an issue?

**Comment by jrappen** [comment]
@wbond I did that, nothing weird I could find however. Removing the file and having Package Control re-download it fixed it for me.
