### ISSUE TITLE
"OS error" message not going away.

### ISSUE THREAD

**Issue by CasperBraske** [divmain/GitSavvy#799]
- Sublime Text version: 3143
- Git version number: 2.7.4
- OS type and version: Ubuntu Linux 16.04

I got stuck with the message bellow after closing and reopening Sublime for the first time after adding the package. After closing the dialogue window, the message got right back not allowing me to do anything.
`GitSavvy encountered an OS error: `
`[Errno 2] No such file or directory: '/var/www/html/[path skipped]/.git/rebase-apply/head-name'`

I had to remove GitSavvy manually from the filesystem.

Best regards.

**Comment by 3v1n0** [comment]
Same here...

It happens to me when I create a `git rebase -i HEAD~5` for example from terminal and I've the rebase view open in my sublime text... It stays there until I've finished the rebase.

![immagine](https://user-images.githubusercontent.com/345675/32083272-358e6308-ba87-11e7-8e04-2545ecbb6e9a.png)

**Comment by 3v1n0** [comment]
Same is also when doing a `git apply` with a patch that doesn't merge cleanly

**Comment by randy3k** [comment]
It is related to the `safe_open` method at https://github.com/divmain/GitSavvy/blob/c93544dac91802f477976c2bbad92640ac77b5e1/core/git_mixins/rewrite.py#L220-L220

It may be necessary to check if the file exists or not before runnign `safe_open`? 

@stoivo Why `safe_open` is used instead of just `open`?  I don't understand why it is "safe"?

**Comment by asfaltboy** [comment]
@randy3k #640 that it's safe to the calling function, but rather that it doesn't simply propagate the exception, assisting users understand what is their issue.

Using it in rebase may be the source of the issue though, because these are not user created files, and the related commands possibly expect the exception ...

**Comment by randy3k** [comment]
> Using it in rebase may be the source of the issue though, because these are not user created files, and the related commands possibly expect the exception ...

👍

**Comment by stoivo** [comment]
Should me fixed on dev
