### ISSUE TITLE
"git: commit" option doesn't work while "git: quick commit" works

### ISSUE THREAD

**Issue by DrDonkey** [divmain/GitSavvy#844]
And "git: commit including staged file" also doesn't work.

**Comment by stoivo** [comment]
Please will out the issue template 

If you encounter a bug, please check for an open issue that already captures the problem you've run into.  If it doesn't exist yet, create it!

Please include the following information when filing a bug:

- Sublime Text version number
- Git version number
- OS type and version
- Console error output
- A description of the problem.
- Steps to reproduce, if possible
- If the bug is caused by a failing command, [include a debug log](docs/debug.md#providing-a-debug-log).

**Comment by stoivo** [comment]
Feel free to reopen
