### ISSUE TITLE
Repeat last commit message

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#89]
This is something I sometimes find nice of GIT ides, I appreciate is not all the time, but sometimes you are working on something and you have some common text on the commit message, like a module prefix or something and it's nice to maybe just have the last commit message already pre-filled, maybe commented.

Again I think this should be configurable.

**Comment by yyyc514** [comment]
You're not talking about amend but rather a sequence of commits that are related?  Why not put them all in a branch then merge?

**Comment by hanoii** [comment]
@yyyc514, well that's a possibility, but I do not do that very often. Rather I am working on something and then do a commit, but further commits might be necessary after some tests and a lot are related. I sometimes prefix the commit message with a module name or something and lazy enough, sometimes its good to have the old commit message already filled in. It is something that a log of GUIs do.

**Comment by stoivo** [comment]
I have to option
1. A new command that will be called `git: commit with prefilled of previous message`
2. A new setting called 'prefill_commit_with_previus_commit_message'

I do refer the first. 

Most of the time, I find myself just type those to words that is the same. And if I really badly don't want to type, I will open `Git log`, find my commit, copy the text I want. In is sense, would we like to add these to GitSavvy.

**Comment by divmain** [comment]
@hanoii, assuming you'd still be interested in this - can you provide a link to user documentation or screenshots of other tools that do this?  This seems like strange UX, so I'd like to see how others have done it.  Thanks!

**Comment by hanoii** [comment]
You know what, I just checked two of the tools I kind of remember seeing this and couldn't find it :).

And to be honest, I lately using a different approach to commit messages so it's not a current need right now for me, but I do see some benefits.

I was thinking something more in the line of a shortcut, not sure if that's possible, like when hit on the commit window you could pull one of the last commit logs.

Are there keybindings specific to a window? Otherwise your configuration for showing the last commits commented outs should work very good as well.

**Comment by stoivo** [comment]
Yes we can have specific short-cuts for each view and do. 
Like when you press `SUPER + s` to sign a commit? Add something like  `SUPER + l` to pull the last commit?

Be already have a this text in the commit view
```
## To make a commit, type your commit message and press SUPER-ENTER. To cancel
## the commit, close the window. To sign off on the commit, press SUPER-S.
```

To make this in the UI we should it the same. Also I don't like to add another configuration. There is already many

**Comment by divmain** [comment]
This is an interesting problem, and relates to other issues I've been considering lately.  Basically, people have varying preferences for what they'd like to see in the commit view.  Off the top of my head:

- `git status` output
- `git commit --dryrun` output
- `git diff --cached` output
- something like `git log -n 5 --format=format:"%h %s"` (this ticket)

Since everybody wants something different, maybe we should make this directly configurable by allowing something in `GitSavvy.sublime_settings` like:

```json
{
  "git_commit_summary": [
    ["git", "commit", "--dryrun"],
    ["git", "diff", "--cached"]
  ]
}
```

Where the commit view would show the area to enter the commit message, followed by the helper text, followed by the `git commit --dryrun` output, followed by the `git diff --cached` output.  The only downside here is syntax highlighting.  Users who are displaying the diff, for example, will want it to be highlighted that way.

Maybe we could be even more complex and attempt nested syntax areas for those sections independently.  Then the config would look something like:

```json
{
  "git_commit_summary": [{
    "content": ["git", "commit", "--dryrun"],
    "syntax": null
  }, {
    "content": ["git", "diff", "--cached"],
    "syntax": "Packages/GitSavvy/syntax/diff.tmLanguage"
  }]
}
```

That increases the config complexity, but it would definitely give people flexibility.  Alternately, we could avoid displaying all of these simultaneously, and instead provide a keyboard shortcut that users could use to cycle through the options they specified.

Thoughts?

**Comment by hanoii** [comment]
Well, GitSavvy is for TechSavvy guys so I really wouldn't cut down on configurations only because they are complex.

I like your idea of having as much flexibility as possible. Cycling through the different configured settings is also great although I might do that as a second enhancement as I see this used only in very specific use cases in which cycling might not add much use.

The log though, what I see as a nice addition, so have a shortcut that display the log in the usual selection pallet, so you can even use sublime fuzzy search to search through the logs.

Does it make sense?

**Comment by stoivo** [comment]
We definitely need to have syntax highlighting. Since we need this I think is it nearly impossible to have it all displayed at once. 

Lets take the diff. I think we want to have the same commands as we have for the normal diff interface, like jump to file, maybe toggle which files is displayed. So here we want to run this command. 
```
{
  "caption": "git: diff cached",
  "command": "gs_diff",
  "args": { "in_cached_mode": true }
}
``` 
This will solve issues with syntax and shortcuts.

Than I would change the commit message to 
```
## Close view to abort/cancel commit
## [SUPER-ENTER] Make commit 
## [SUPER-s]     To sign off on the commit
## [SUPER-c]     Open cached diff
## [SUPER-d]     Open Status of changed files
## [SUPER-g]     Open graph for current branch
 

## You may also reference or close a GitHub issue with this commit.  To do so,
## type `#` followed by the `tab` key.  You will be shown a list of issues
## related to the current repo.  You may also type `owner/repo#` plus the `tab`
## key to reference an issue in a different GitHub repo.
```
If we are going with this idea we need to make a command for `status --dry-run`. Where we could make it so you can see the open the diff for one specific file.

**Comment by stoivo** [comment]
Closing this one, it will be followed in #50
