### ISSUE TITLE
Close view if repo not initialized for GitSavvy UI view

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#91]
If the git directory was removed outside of ST and the Status view was active (might affect other GitSavvy views aswell), GitSavvy will ask the user to init a new repo. Upon pressing cancel the same question appears again, and again.

The only way to stop it seems to be to press OK and actually create a new repo.

**Steps to recreate:**
• Open Status view with an existing git repo
• Delete the .git folder outside of ST
• Return to ST

**Desired behavior**
When pressing cancel, display a message in the Status view (and other affected views) letting the user know that GitSavvy requires a git repo. Maybe encourage the user to init a new repo manually.

**Comment by divmain** [comment]
Hmm interesting.  I think in this case, a message should be displayed and the status/inline-diff/whatever view should be closed.

Otherwise, we'd have to either 1) riddle the code base with checks in random places, or 2) disable GitSavvy for a view that could never be recovered from (like if the user returned to the terminal, did `git init`, and returned back to the view).

**Comment by alextegelid** [comment]
True. Closing the view makes more sense!

**Comment by divmain** [comment]
This is related to #137 and 845995b.  Getting the all possible paths to `self.git` in a dashboard to behave the right way turned out to be an onerous path.

For a simpler alternative that should be adequate for now, the user will be offered initialization once per view - after that, it will fail and just show the Git output.  For dashboards/interfaces, this should suffice, as it'll be obvious that GitSavvy won't work unless you initialize.  For normal views, it should provide enough context for the user to know what to expect.

I may re-visit this if my solution turns out to be insufficient.
