### ISSUE TITLE
Add/remove hunks and lines in "diff all files" view

### ISSUE THREAD

**Issue by jipumarino** [divmain/GitSavvy#98]
Currently, this can only be done in the "diff file inline" view.

**Comment by divmain** [comment]
Hi @jipumarino - if you run `git: diff`, you are able to stage individual hunks from the resulting view (see [here](https://github.com/divmain/GitSavvy/blob/master/docs/staging.md#git-diff)).  You can also remove hunks from the index using `git: diff (cached)`.

I don't have plans to support staging individual lines from this view, mostly because of the complexity involved that was already solved with the inline-diff view.  However, if you're looking for more exact control over what is staged, I may add functionality to edit the diff before it is applied to the index (see #42).

**Comment by jipumarino** [comment]
Oh, sorry. I tried using the same shortcuts as in the file diff. Thanks!

**Comment by divmain** [comment]
No worries!
